# S&P 500 — Pipeline de Construção da Base de Dados
## TCC: Pair Trading

Este notebook organiza o pipeline completo de construção da base de preços do S&P 500,
livre de viés de sobrevivência, para uso no TCC de pair trading.

---

### Fluxo geral

```
ETAPA 1 │ Importações e configuração de caminhos
ETAPA 2 │ Carregar a base original do professor (1990/S2 – 2015/S1)
ETAPA 3 │ Carregar o Periods.csv e construir o mapeamento semestral
ETAPA 4 │ Unir base de preços + mapeamento de períodos → sp500_with_periods
ETAPA 5 │ Carregar e validar os constituintes históricos do S&P 500
ETAPA 6 │ Gerar snapshots semestrais (2015/S1 – 2025/S2) e lista de tickers
ETAPA 7 │ Coletar preços via Yahoo Finance (com checkpoint de retomada)
```

> **Sobre viés de sobrevivência:** a base inclui todas as empresas que já fizeram
> parte do índice, mesmo as que faliram, foram adquiridas ou foram removidas.
> Isso é essencial para evitar que os resultados do backtest sejam inflados por
> considerar apenas as empresas que "sobreviveram".

---
## Etapa 1 — Importações e configuração de caminhos

Centralizar todos os caminhos de arquivo aqui facilita mover o projeto entre
máquinas: basta ajustar `BASE_DIR`.

In [80]:
import pandas as pd
import numpy as np
import yfinance as yf
import time
from pathlib import Path

print(f"pandas   {pd.__version__}")
print(f"yfinance {yf.__version__}")

# Nota sobre versões do yfinance:
# Em versões recentes (≥ 0.2.x), ao usar auto_adjust=False, o retorno inclui
# as colunas: Open, High, Low, Close, Adj Close, Volume
# A coluna 'Close' é o preço sem ajuste de dividendos (split-adjusted apenas)
# A coluna 'Adj Close' inclui ajuste de dividendos — NÃO usar para esta base

pandas   2.2.3
yfinance 1.2.0

In [81]:
# ── Caminho raiz do projeto ───────────────────────────────────────────────────
# Ajuste aqui se mover os arquivos de lugar.
BASE_DIR        = Path(r"C:\Users\jvlei\Desktop\TCC-pair-trading\data_bases")
BASE_DIR_OUTPUT = BASE_DIR / "output"

# ── Arquivos de entrada ───────────────────────────────────────────────────────
PATH_DB       = BASE_DIR / "Pt_formatted.csv"                                   # Base do professor (fatia de 4k linhas para exploração)
PATH_DB_FULL  = BASE_DIR / "Pt_formatted.csv"                             # Base completa (6426 linhas) — usar para validação de datas
PATH_PERIODS  = BASE_DIR / "Periods.csv"                                        # Dias de pregão por semestre
PATH_SP500HIS = BASE_DIR / "S&P 500 Historical Components & Changes(01-17-2026).csv"  # Constituintes históricos

# ── Arquivos de saída (gerados por este notebook) ─────────────────────────────
PATH_DB_PERIODS   = BASE_DIR_OUTPUT / "sp500_with_periods.csv"                  # Base + metadados de período
PATH_SNAPSHOTS    = BASE_DIR_OUTPUT / "snapshots_semestrais.csv"                # Constituintes por semestre
PATH_TICKERS      = BASE_DIR_OUTPUT / "tickers_a_coletar.csv"                   # Tickers únicos + janela de coleta
PATH_REPORT       = BASE_DIR_OUTPUT / "coleta_report.csv"                       # Status da coleta (ok/delisted/erro)
DIR_PRICES        = BASE_DIR_OUTPUT / "prices"                                   # Um CSV por ticker

DIR_PRICES.mkdir(parents=True, exist_ok=True)

print("Caminhos configurados:")
for name, p in [
    ("Base do professor", PATH_DB),
    ("Periods.csv",       PATH_PERIODS),
    ("Constituintes S&P", PATH_SP500HIS),
]:
    status = "✅ existe" if p.exists() else "❌ NÃO encontrado"
    print(f"  {status}  {p.name}")

Caminhos configurados:
  ✅ existe  Pt_formatted.csv
  ✅ existe  Periods.csv
  ✅ existe  S&P 500 Historical Components & Changes(01-17-2026).csv

---
## Etapa 2 — Base original do professor (1990/S2 – 2015/S1)

Formato wide: cada linha é um dia de pregão, cada coluna é um ticker.
Os valores são preços de fechamento ajustados por splits.
Empresas que faliram ou foram removidas do índice mantêm seus dados
históricos — identificáveis pelo sufixo `Q` no ticker (ex: `ENRNQ` = Enron).

In [82]:
db = pd.read_csv(PATH_DB)

print(f"Shape: {db.shape[0]:,} linhas × {db.shape[1]:,} colunas")
print(f"Primeiros tickers: {db.columns[:8].tolist()}")
print(f"Últimos  tickers: {db.columns[-5:].tolist()}")

Shape: 6,426 linhas × 1,100 colunas
Primeiros tickers: ['UN', '1005945D', '162007Q', 'RDPL', 'BGG', 'SKY', 'GOSHA', 'HSY']
Últimos  tickers: ['EQIX', '1436513D', '1431816D', 'SPGI', '1448062D']

In [83]:
# Inspeção rápida: empresas famosas para verificar que os valores fazem sentido.
# Todos os valores são split-adjusted, então AAPL em 1990 aparece como ~$1.
spot_check = {
    "AAPL": "Apple — ~$1 em 1990 (split-adjusted)",
    "GE":   "GE — presente desde o início",
    "XOM":  "ExxonMobil",
}
for ticker, nota in spot_check.items():
    if ticker in db.columns:
        primeiros = db[ticker].dropna().head(3).round(4).tolist()
        print(f"{ticker:6s} ({nota}): {primeiros}")

AAPL   (Apple — ~$1 em 1990 (split-adjusted)): [1.3753, 1.3753, 1.3596]
GE     (GE — presente desde o início): [2.8747, 2.9053, 2.8645]
XOM    (ExxonMobil): [5.6624, 5.6328, 5.5438]

---
## Etapa 3 — Mapeamento de períodos (Periods.csv)

`Periods.csv` contém a contagem oficial de dias de pregão da NYSE por semestre,
fornecida pelo professor. Essa contagem é usada como **fonte verdadeira** para
mapear cada linha da base a um período — não usamos aproximações de calendário.

**Estrutura dos 51 semestres:**
- `idx 0`  → `1990/S2` (jul–dez 1990) ← a base começa no 2º semestre de 1990
- `idx 1`  → `1991/S1` (jan–jun 1991)
- `idx 2`  → `1991/S2` ...
- `idx 50` → `2015/S1` (jan–jun 2015) ← último semestre da base do professor

**Âncoras de validação:**
- `2001/S2` tem **123 dias** (único semestre <124) → reflexo do fechamento da NYSE após o 11/set
- `GOOGL` aparece pela primeira vez na linha **3.563** → cai em `2004/S2` (IPO ago/2004)

In [84]:
# Carregar sem cabeçalho (a primeira linha já é dado)
periods_raw = pd.read_csv(PATH_PERIODS, header=None)
periods_raw.columns = ["dias_sem", "nan1", "nan2", "dias_ano"]
periods_raw = periods_raw[["dias_sem", "dias_ano"]]

print(f"Semestres encontrados: {len(periods_raw)}")
print(f"Total de dias de pregão: {periods_raw['dias_sem'].sum():,}")
print()
print(periods_raw)

Semestres encontrados: 51
Total de dias de pregão: 6,425

    dias_sem  dias_ano
0        127     252.0
1        125     253.0
2        128     254.0
3        126     254.0
4        128     252.0
5        124     252.0
6        128     253.0
7        125     252.0
8        127     253.0
9        126     252.0
10       126     252.0
11       126     254.0
12       128     253.0
13       125     253.0
14       128     252.0
15       124     252.0
16       128     252.0
17       124     252.0
18       128     254.0
19       126     252.0
20       126     251.0
21       125     248.0
22       123     247.0
23       124     252.0
24       128     252.0
25       124     252.0
26       128     252.0
27       124     252.0
28       128     253.0
29       125     252.0
30       127     252.0
31       125     251.0
32       126     250.0
33       124     251.0
34       127     252.0
35       125     253.0
36       128     252.0
37       124     252.0
38       128     252.0
39       124     252.0
40       128     253.0
41       125     252.0
42       127     252.0
43       125     250.0
44       125     249.0
45       124     252.0
46       128     252.0
47       124     252.0
48       128     252.0
49       124     251.0
50       127       NaN

In [85]:
# Construir mapeamento linha → semestre usando Periods.csv como fonte verdadeira.
# Regra de indexação:
#   idx 0          → 1990/S2 (caso especial)
#   idx ímpar ≥ 1  → S1 do ano (1990 + idx // 2)
#   idx par   ≥ 2  → S2 do ano (1990 + idx // 2)

registros = []
linha_atual = 0

for i, row in periods_raw.iterrows():
    n_dias = int(row["dias_sem"])

    if i == 0:
        ano, sem = 1990, 2
        inicio_sem, fim_sem = "1990-07-01", "1990-12-31"
    else:
        ano = 1990 + (i // 2)
        if i % 2 == 1:      # ímpar → primeiro semestre
            sem = 1
            inicio_sem = f"{ano}-01-01"
            fim_sem    = f"{ano}-06-30"
        else:               # par → segundo semestre
            sem = 2
            inicio_sem = f"{ano}-07-01"
            fim_sem    = f"{ano}-12-31"

    for d in range(n_dias):
        registros.append({
            "linha":           linha_atual,
            "ano":             ano,
            "semestre":        sem,
            "periodo":         f"{ano}/S{sem}",
            "inicio_semestre": inicio_sem,
            "fim_semestre":    fim_sem,
            "dia_no_semestre": d + 1,
            "total_dias_sem":  n_dias,
            "total_dias_ano":  row["dias_ano"],
        })
        linha_atual += 1

mapa = pd.DataFrame(registros)
print(f"Linhas mapeadas: {len(mapa):,}")
print()
print("Início:")
print(mapa.head(3)[["linha", "periodo", "dia_no_semestre", "total_dias_sem"]])
print("\nFim:")
print(mapa.tail(3)[["linha", "periodo", "dia_no_semestre", "total_dias_sem"]])

Linhas mapeadas: 6,425

Início:
   linha  periodo  dia_no_semestre  total_dias_sem
0      0  1990/S2                1             127
1      1  1990/S2                2             127
2      2  1990/S2                3             127

Fim:
      linha  periodo  dia_no_semestre  total_dias_sem
6422   6422  2015/S2              125             127
6423   6423  2015/S2              126             127
6424   6424  2015/S2              127             127

In [86]:
# ── Validações do mapeamento ──────────────────────────────────────────────────

# Validação 1: 2001/S2 deve ter exatamente 123 dias (11 de setembro)
dias_2001s2 = len(mapa[mapa["periodo"] == "2001/S2"])
ok1 = dias_2001s2 == 123
print(f"{'✅' if ok1 else '❌'} 2001/S2 tem {dias_2001s2} dias (esperado: 123 — efeito 11/set)")

# Validação 2: GOOGL deve aparecer em 2004/S2 (IPO agosto/2004)
if "GOOGL" in db.columns:
    idx_googl = db["GOOGL"].first_valid_index()
    periodo_googl = mapa.iloc[idx_googl]["periodo"]
    dia_googl = mapa.iloc[idx_googl]["dia_no_semestre"]
    ok2 = periodo_googl == "2004/S2"
    print(f"{'✅' if ok2 else '❌'} GOOGL aparece na linha {idx_googl} → {periodo_googl}, "
          f"dia {dia_googl} do semestre (esperado: 2004/S2)")

# Validação 3: diferença de linhas entre db e mapa
diff = abs(len(db) - len(mapa))
ok3 = diff <= 1
print(f"{'✅' if ok3 else '⚠️ '} db tem {len(db):,} linhas, mapa tem {len(mapa):,} "
      f"(diferença: {diff} — ok se ≤ 1)")

✅ 2001/S2 tem 123 dias (esperado: 123 — efeito 11/set)
✅ GOOGL aparece na linha 3563 → 2004/S2, dia 35 do semestre (esperado: 2004/S2)
✅ db tem 6,426 linhas, mapa tem 6,425 (diferença: 1 — ok se ≤ 1)

---
## Etapa 4 — Unir base de preços com metadados de período

Adiciona 8 colunas de contexto temporal no início da base:
`ano`, `semestre`, `periodo`, `inicio_semestre`, `fim_semestre`,
`dia_no_semestre`, `total_dias_sem`, `total_dias_ano`.

O resultado é salvo em `sp500_with_periods.csv`.

In [87]:
# Ajustar tamanho do mapa para coincidir com db (diferença de ±1 é normal)
if len(mapa) > len(db):
    mapa_alinhado = mapa.iloc[:len(db)].reset_index(drop=True)
elif len(mapa) < len(db):
    extras = pd.DataFrame([{
        "linha": len(mapa) + k, "ano": np.nan, "semestre": np.nan,
        "periodo": np.nan, "inicio_semestre": np.nan, "fim_semestre": np.nan,
        "dia_no_semestre": np.nan, "total_dias_sem": np.nan, "total_dias_ano": np.nan,
    } for k in range(len(db) - len(mapa))])
    mapa_alinhado = pd.concat([mapa, extras], ignore_index=True)
else:
    mapa_alinhado = mapa.reset_index(drop=True)

cols_periodo = [
    "ano", "semestre", "periodo",
    "inicio_semestre", "fim_semestre",
    "dia_no_semestre", "total_dias_sem", "total_dias_ano",
]

sp500_with_periods = pd.concat(
    [mapa_alinhado[cols_periodo], db.reset_index(drop=True)],
    axis=1
)

print(f"Shape final: {sp500_with_periods.shape[0]:,} linhas × {sp500_with_periods.shape[1]:,} colunas")
print(f"Primeiro período: {sp500_with_periods['periodo'].iloc[0]}")
print(f"Último  período: {sp500_with_periods['periodo'].dropna().iloc[-1]}")

Shape final: 6,426 linhas × 1,108 colunas
Primeiro período: 1990/S2
Último  período: 2015/S2

In [88]:
# Salvar a base unificada
sp500_with_periods.to_csv(PATH_DB_PERIODS, index=False)
print(f"✅ Salvo em: {PATH_DB_PERIODS.name}")
print()

# Amostra para inspeção visual
sp500_with_periods[["periodo", "ano", "semestre", "dia_no_semestre", "AAPL", "GE", "XOM"]].head(5)

✅ Salvo em: sp500_with_periods.csv

   periodo     ano  semestre  dia_no_semestre    AAPL      GE     XOM
0  1990/S2  1990.0       2.0              1.0  1.3753  2.8747  5.6624
1  1990/S2  1990.0       2.0              2.0  1.3753  2.9053  5.6328
2  1990/S2  1990.0       2.0              3.0  1.3596  2.8645  5.5438
3  1990/S2  1990.0       2.0              4.0  1.3987  2.8798  5.6624
4  1990/S2  1990.0       2.0              5.0  1.4573  2.9104  5.6180

---
## Etapa 5 — Constituintes históricos do S&P 500 (1996–2026)

O arquivo `S&P 500 Historical Components & Changes` (repositório `fja05680/sp500`)
registra cada mudança de composição do índice desde 1996. Cada linha representa
uma data em que a composição mudou, com a lista completa de tickers naquele momento.

Para saber quem estava no índice em qualquer data D: buscamos a última linha
com `date ≤ D`.

**Validações usadas:**
- Tesla (`TSLA`): entrou em **21/dez/2020** (não antes)
- Facebook/Meta: era `FB` até **08/jun/2022**, virou `META` em 09/jun/2022
- Lehman Brothers (`LEHMQ`): removida após a falência em setembro de 2008

In [89]:
hist = pd.read_csv(PATH_SP500HIS)
hist["date"] = pd.to_datetime(hist["date"])
hist["n_tickers"] = hist["tickers"].apply(lambda x: len(x.split(",")))

print(f"Snapshots carregados: {len(hist):,}")
print(f"Período coberto: {hist['date'].min().date()} → {hist['date'].max().date()}")
print(f"Tickers por snapshot: min={hist['n_tickers'].min()}, max={hist['n_tickers'].max()}, "
      f"média={hist['n_tickers'].mean():.0f}")

Snapshots carregados: 2,705
Período coberto: 1996-01-02 → 2026-01-14
Tickers por snapshot: min=487, max=507, média=497

In [90]:
def get_constituents(date_str):
    """Retorna o conjunto de tickers do S&P 500 em uma data específica."""
    date = pd.to_datetime(date_str)
    subset = hist[hist["date"] <= date]
    if len(subset) == 0:
        return set()
    return set(subset.iloc[-1]["tickers"].split(","))

# ── Validações cruzadas ───────────────────────────────────────────────────────
validations = [
    ("TSLA",  True,  "2020-12-21", "Tesla entrou em 21/dez/2020"),
    ("TSLA",  False, "2020-12-20", "Tesla NÃO estava em 20/dez/2020"),
    ("FB",    True,  "2022-06-08", "Facebook ainda era FB em 08/jun/2022"),
    ("META",  True,  "2022-06-09", "Meta a partir de 09/jun/2022"),
    ("LEHMQ", False, "2009-01-01", "Lehman removida após falência em 2008"),
    ("AMZN",  True,  "2023-12-31", "Amazon sempre presente"),
]

all_ok = True
for ticker, should_be_in, date_str, note in validations:
    tickers = get_constituents(date_str)
    present = ticker in tickers
    ok = present == should_be_in
    if not ok:
        all_ok = False
    status = "✅" if ok else "❌"
    print(f"  {status} {ticker:6s} {'IN ' if should_be_in else 'OUT'}  {date_str}  — {note}")

print()
print("Todas as validações passaram ✅" if all_ok else "⚠️  Verificar falhas acima.")

  ✅ TSLA   IN   2020-12-21  — Tesla entrou em 21/dez/2020
  ✅ TSLA   OUT  2020-12-20  — Tesla NÃO estava em 20/dez/2020
  ✅ FB     IN   2022-06-08  — Facebook ainda era FB em 08/jun/2022
  ✅ META   IN   2022-06-09  — Meta a partir de 09/jun/2022
  ✅ LEHMQ  OUT  2009-01-01  — Lehman removida após falência em 2008
  ✅ AMZN   IN   2023-12-31  — Amazon sempre presente

Todas as validações passaram ✅

---
## Etapa 6 — Snapshots semestrais e lista de tickers para coleta

Para cada semestre de **2015/S1** a **2025/S2**, extraímos a composição do
índice no último dia do semestre (30/jun ou 31/dez). Isso define quem estava
"dentro" do índice naquele período — respeitando o critério anti-survivorship bias.

O resultado são dois arquivos:
- `snapshots_semestrais.csv` — composição completa por semestre
- `tickers_a_coletar.csv` — lista de tickers únicos com janela de coleta no Yahoo

In [91]:
# Definir os semestres de 2015/S1 a 2025/S2
semesters = []
for ano in range(2015, 2026):
    for sem in [1, 2]:
        inicio = f"{ano}-01-01" if sem == 1 else f"{ano}-07-01"
        fim    = f"{ano}-06-30" if sem == 1 else f"{ano}-12-31"
        semesters.append({
            "periodo":       f"{ano}/S{sem}",
            "ano":           ano,
            "semestre":      sem,
            "inicio":        inicio,
            "fim":           fim,
            "snapshot_date": fim,   # composição no último dia do semestre
        })

# Gerar snapshots
snap_rows = []
for s in semesters:
    t = get_constituents(s["snapshot_date"])
    snap_rows.append({**s, "n_tickers": len(t), "tickers": ",".join(sorted(t))})

snap_df = pd.DataFrame(snap_rows)
snap_df.to_csv(PATH_SNAPSHOTS, index=False)

print(f"Snapshots gerados: {len(snap_df)} semestres")
print()
print(snap_df[["periodo", "n_tickers"]].to_string(index=False))

Snapshots gerados: 22 semestres

periodo  n_tickers
2015/S1        499
2015/S2        502
2016/S1        505
2016/S2        506
2017/S1        506
2017/S2        505
2018/S1        506
2018/S2        505
2019/S1        505
2019/S2        505
2020/S1        505
2020/S2        505
2021/S1        505
2021/S2        505
2022/S1        503
2022/S2        503
2023/S1        503
2023/S2        503
2024/S1        503
2024/S2        503
2025/S1        503
2025/S2        503

In [92]:
# Construir lista de todos os tickers únicos no período de extensão (excluindo 2015/S1,
# que já está na base do professor).
ext_df = snap_df[snap_df["periodo"] != "2015/S1"].copy()

all_tickers = set()
for _, row in ext_df.iterrows():
    all_tickers.update(row["tickers"].split(","))

# Para cada ticker: janela de coleta (primeiro e último semestre em que esteve no índice)
ticker_rows = []
for ticker in sorted(all_tickers):
    periods_in = [
        row["periodo"]
        for _, row in ext_df.iterrows()
        if ticker in row["tickers"].split(",")
    ]
    first_sem, last_sem = periods_in[0], periods_in[-1]
    f_ano, f_s = int(first_sem[:4]), int(first_sem[-1])
    l_ano, l_s = int(last_sem[:4]),  int(last_sem[-1])
    start_date = f"{f_ano}-01-01" if f_s == 1 else f"{f_ano}-07-01"
    end_date   = f"{l_ano}-06-30" if l_s == 1 else f"{l_ano}-12-31"

    ticker_rows.append({
        "ticker":       ticker,
        "first_period": first_sem,
        "last_period":  last_sem,
        "n_periods":    len(periods_in),
        "start_date":   start_date,
        "end_date":     end_date,
        "status":       "pending",
    })

tickers_df = pd.DataFrame(ticker_rows)
tickers_df.to_csv(PATH_TICKERS, index=False)

# Resumo de turnover
t_2015s1 = set(snap_df[snap_df["periodo"] == "2015/S1"]["tickers"].iloc[0].split(","))
t_2025s2 = set(snap_df[snap_df["periodo"] == "2025/S2"]["tickers"].iloc[0].split(","))
print(f"Tickers únicos para coletar: {len(tickers_df)}")
print(f"  Permaneceram (2015→2025):  {len(t_2015s1 & t_2025s2)}")
print(f"  Entraram no índice:        {len(t_2025s2 - t_2015s1)}")
print(f"  Saíram do índice:          {len(t_2015s1 - t_2025s2)}")
print()
print(f"Arquivo salvo: {PATH_TICKERS.name}")

Tickers únicos para coletar: 725
  Permaneceram (2015→2025):  320
  Entraram no índice:        183
  Saíram do índice:          179

Arquivo salvo: tickers_a_coletar.csv

---
## Etapa 7 — Validação do tipo de ajuste de preço

Antes de coletar os dados do Yahoo, precisamos confirmar qual tipo de preço
a base do professor usa — para garantir consistência na junção das bases.

### O que descobrimos

A base do professor usa **`Close` sem ajuste de dividendos** (split-adjusted apenas),
**não** o `Adj Close` que inclui dividendos.

**Evidência:** ao comparar os últimos valores da base do professor com o
Yahoo Finance no mesmo período, o `ratio` com `Close` bruto fica ≈ 1.0
para MSFT, KO, JNJ e XOM, enquanto o `ratio` com `Adj Close` diverge
significativamente (1.15×, 1.38×, 1.33×, 1.56×).

### Por que a validação exige a base completa

O script usa `Periods.csv` para mapear linha → data exata, evitando o
desalinhamento causado por feriados da NYSE. A base parcial (4k linhas)
usa `bdate_range` como proxy e acumula ~2-3 dias de erro até o final —
suficiente para inverter a correlação dos retornos diários e gerar falsos
negativos na validação.

### Consequência para a coleta (Etapa 8)

Usar `auto_adjust=False` e a coluna `Close` no yfinance — não `Adj Close`.

In [93]:
db_full

,UN,1005945D,162007Q,RDPL,BGG,SKY,GOSHA,HSY,NMK,WLB,...,MNST,O,JBHT,BXLT,ENDP,EQIX,1436513D,1431816D,SPGI,1448062D
1990-07-02,3.3082,11.7377,32.6951,10.2566,3.6022,7.723,13.6570,5.3707,10.9995,23.0656,...,NaN,NaN,2.8041,NaN,NaN,NaN,1.4481,2.7908,3.875790,NaN
1990-07-03,3.3321,11.8106,32.1859,10.2396,3.5747,7.657,13.7545,5.3175,10.9022,23.0656,...,NaN,NaN,2.7715,NaN,NaN,NaN,1.4655,2.7288,3.858865,NaN
1990-07-04,3.2699,11.5919,30.7599,10.1207,3.4922,7.591,13.4619,5.2112,10.7075,23.0656,...,NaN,NaN,2.7715,NaN,NaN,NaN,1.4655,2.6668,3.841940,NaN
1990-07-05,3.3082,11.6648,32.0840,10.1886,3.4647,7.657,13.6570,5.3175,10.8048,23.0656,...,NaN,NaN,2.7715,NaN,NaN,NaN,1.4713,2.7288,3.841940,NaN
1990-07-06,3.2986,11.6648,31.6766,10.2226,3.4510,7.591,13.6570,5.3884,10.8048,22.8278,...,NaN,NaN,2.6737,NaN,NaN,NaN,1.4365,2.6357,3.841940,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2015-12-21,43.6300,NaN,NaN,NaN,17.0200,NaN,NaN,90.3400,NaN,6.4700,...,147.47,51.1365,72.6700,39.33,62.71,297.35,39.8606,NaN,94.632677,NaN
2015-12-22,43.5600,NaN,NaN,NaN,16.9300,NaN,NaN,90.3200,NaN,6.3800,...,148.82,50.9280,72.9700,39.27,62.62,297.19,39.6647,NaN,96.685191,NaN
2015-12-23,43.7100,NaN,NaN,NaN,16.7100,NaN,NaN,90.3900,NaN,5.9900,...,148.16,51.3748,72.8800,38.49,61.82,300.91,39.0673,NaN,96.201661,NaN
2015-12-24,44.2300,NaN,NaN,NaN,17.8500,NaN,NaN,90.9800,NaN,5.8900,...,150.17,51.8016,73.5100,39.39,62.49,304.98,39.6843,NaN,96.181929,NaN
2015-12-25,44.0400,NaN,NaN,NaN,17.6200,NaN,NaN,90.6000,NaN,5.7700,...,150.24,51.7329,73.0300,39.10,62.42,302.69,39.4003,NaN,98.678493,NaN

In [94]:
# ── Validação do ajuste de preço ──────────────────────────────────────────────
# Compara os últimos valores da base do professor com o Yahoo Finance,
# usando as datas reais extraídas do Periods.csv (sem feriados incorretos).
#
# Requer a base COMPLETA (6426 linhas). Se ainda não tiver o arquivo completo,
# comente este bloco e prossiga — a conclusão já é conhecida: usar Close bruto.

TICKERS_VALIDACAO = ["MSFT", "KO", "JNJ", "XOM"]
N_DIAS_COMP       = 20    # pregões finais da base para comparar
TOLERANCIA_RATIO  = 0.01  # diferença máxima aceitável no ratio (1%)

if not PATH_DB_FULL.exists():
    print("⚠️  Base completa não encontrada. Pulando validação.")
    print("   Conclusão conhecida: usar auto_adjust=False, coluna 'Close'.")
else:
    # Carregar base completa e reconstruir mapa de datas via Periods.csv
    print("Carregando base completa e mapa de períodos...")
    db_full = pd.read_csv(PATH_DB_FULL)

    periods_v = pd.read_csv(PATH_PERIODS, header=None)
    periods_v.columns = ["dias_sem", "nan1", "nan2", "dias_ano"]

    # Reconstruir datas usando pd.bdate_range corrigido por semestre
    # (cada semestre tem início certo; erro de feriados fica contido ao semestre)
    datas = []
    for i, row in periods_v.iterrows():
        n = int(row["dias_sem"])
        if i == 0:   ini = "1990-07-02"
        else:
            ano = 1990 + (i // 2)
            ini = f"{ano}-01-02" if i % 2 == 1 else f"{ano}-07-02"
        datas.extend(pd.bdate_range(start=ini, periods=n))

    n_alinhar = min(len(db_full), len(datas))
    db_full = db_full.iloc[:n_alinhar]  # ← add this line
    db_full.index = pd.DatetimeIndex(datas[:n_alinhar])

    print(f"  Base: {len(db_full):,} linhas | última data mapeada: {db_full.index[-1].date()}")
    print()

    resultados = []
    for ticker in TICKERS_VALIDACAO:
        if ticker not in db_full.columns:
            print(f"{ticker}: não encontrado na base"); continue

        serie_prof = db_full[ticker].dropna().tail(N_DIAS_COMP)
        if len(serie_prof) < 5:
            print(f"{ticker}: dados insuficientes"); continue

        d_ini = serie_prof.index[0].strftime("%Y-%m-%d")
        d_fim = (serie_prof.index[-1] + pd.Timedelta(days=5)).strftime("%Y-%m-%d")

        try:
            raw = yf.download(ticker, start=d_ini, end=d_fim,
                              auto_adjust=False, progress=False)
            if hasattr(raw.columns, "levels"):
                raw.columns = raw.columns.get_level_values(0)
            if raw is None or len(raw) == 0:
                print(f"{ticker}: sem dados no Yahoo"); continue

            idx_comum = serie_prof.index.intersection(raw.index)
            if len(idx_comum) < 3:
                print(f"{ticker}: apenas {len(idx_comum)} datas em comum"); continue

            prof     = serie_prof.loc[idx_comum]
            y_close  = raw["Close"].loc[idx_comum]
            y_adj    = raw["Adj Close"].loc[idx_comum]

            ratio_close = (prof / y_close).replace([float("inf"), float("-inf")], float("nan")).dropna()
            ratio_adj   = (prof / y_adj).replace([float("inf"), float("-inf")], float("nan")).dropna()

            dist_close = abs(ratio_close.mean() - 1.0)
            dist_adj   = abs(ratio_adj.mean()   - 1.0)
            tipo = "Close (sem div)" if dist_close < dist_adj else "Adj Close (com div)"

            icon = "✅" if dist_close < TOLERANCIA_RATIO else "⚠️ "
            print(f"{icon} {ticker:6s} | ratio Close={ratio_close.mean():.4f} (±{ratio_close.std():.4f})"
                  f" | ratio AdjClose={ratio_adj.mean():.4f} (±{ratio_adj.std():.4f})"
                  f" | mais próximo: {tipo}")

            resultados.append({"ticker": ticker, "tipo": tipo,
                                "ratio_close": ratio_close.mean(),
                                "ratio_adj":   ratio_adj.mean()})

        except Exception as e:
            print(f"{ticker}: ERRO — {e}")

    print()
    if resultados:
        tipos = [r["tipo"] for r in resultados]
        dominante = max(set(tipos), key=tipos.count)
        if "Close" in dominante and "sem div" in dominante:
            print("✅ CONCLUSÃO: base do professor usa Close SEM ajuste de dividendos.")
            print("   → Na coleta (Etapa 8): usar auto_adjust=False, coluna 'Close'.")
        else:
            print("⚠️  CONCLUSÃO: base parece usar Adj Close (com dividendos).")
            print("   → Na coleta (Etapa 8): usar auto_adjust=True, coluna 'Close'.")
    else:
        print("Não foi possível concluir — verificar manualmente.")

Carregando base completa e mapa de períodos...
  Base: 6,425 linhas | última data mapeada: 2015-12-25

✅ MSFT   | ratio Close=1.0029 (±0.0176) | ratio AdjClose=1.1480 (±0.0201) | mais próximo: Close (sem div)
✅ KO     | ratio Close=1.0022 (±0.0157) | ratio AdjClose=1.3817 (±0.0216) | mais próximo: Close (sem div)
✅ JNJ    | ratio Close=1.0020 (±0.0159) | ratio AdjClose=1.3287 (±0.0211) | mais próximo: Close (sem div)
✅ XOM    | ratio Close=0.9967 (±0.0298) | ratio AdjClose=1.5549 (±0.0465) | mais próximo: Close (sem div)

✅ CONCLUSÃO: base do professor usa Close SEM ajuste de dividendos.
   → Na coleta (Etapa 8): usar auto_adjust=False, coluna 'Close'.

---
## Etapa 8 — Coleta de preços via Yahoo Finance

Para cada ticker em `tickers_a_coletar.csv`, baixamos o preço de fechamento
**sem ajuste de dividendos** (`auto_adjust=False`, coluna `Close`) — consistente
com a metodologia da base do professor.

> **Por que não usar `Adj Close`?**
> O `Adj Close` do Yahoo desconta dividendos retroativamente toda vez que um
> novo dividendo é pago, alterando valores históricos a cada atualização.
> A base do professor usa apenas ajuste por splits — usar `Adj Close` criaria
> uma descontinuidade artificial na junção das bases em 2015/S1.

**Checkpoint de retomada:** o `coleta_report.csv` é salvo após cada ticker.
Se a coleta for interrompida, basta re-executar — os tickers já coletados
são pulados automaticamente.

**Tickers `DELISTED`:** empresas que faliram ou foram adquiridas não têm
histórico no Yahoo. Elas serão listadas no sumário final para busca em
fontes alternativas (Tiingo ou EODHD).

In [95]:
# ── Configurações da coleta ───────────────────────────────────────────────────
DELAY_ENTRE_REQUESTS = 0.3   # segundos entre requests (evita rate limit do Yahoo)
MIN_LINHAS_VALIDAS   = 10    # mínimo de dias para considerar o download válido

# Recarregar lista para garantir que está atualizada
tickers_df = pd.read_csv(PATH_TICKERS)

# Carregar relatório existente (checkpoint de retomada)
if PATH_REPORT.exists():
    report_df    = pd.read_csv(PATH_REPORT)
    already_done = set(report_df["ticker"].tolist())
    print(f"Retomando: {len(already_done)} já coletados, "
          f"{len(tickers_df) - len(already_done)} restantes.")
else:
    report_df    = pd.DataFrame(columns=["ticker", "status", "n_rows",
                                          "start_date", "end_date", "note"])
    already_done = set()
    print(f"Iniciando coleta de {len(tickers_df)} tickers.")

print(f"Ajuste de preço: Close sem dividendos (auto_adjust=False)")

Iniciando coleta de 725 tickers.
Ajuste de preço: Close sem dividendos (auto_adjust=False)

In [96]:
# ── Loop de coleta ────────────────────────────────────────────────────────────
total = len(tickers_df)

for _, row in tickers_df.iterrows():
    ticker     = row["ticker"]
    start_date = row["start_date"]
    end_date   = row["end_date"]

    if ticker in already_done:
        continue

    n_done = len(already_done) + 1
    print(f"[{n_done:4d}/{total}] {ticker:10s}  {start_date} → {end_date}  ", end="", flush=True)

    try:
        # auto_adjust=False → coluna 'Close' é split-adjusted apenas (sem dividendos)
        # Isso é consistente com a metodologia da base do professor.
        data = yf.download(
            ticker,
            start=start_date,
            end=end_date,
            auto_adjust=False,
            progress=False,
        )

        # Normalizar colunas (yfinance pode retornar MultiIndex)
        if hasattr(data.columns, "levels"):
            data.columns = data.columns.get_level_values(0)

        if data is None or len(data) < MIN_LINHAS_VALIDAS:
            status, note, n_rows = "delisted", "sem dados no Yahoo", 0
            print("DELISTED")
        else:
            # Salvar apenas a coluna Close (sem ajuste de dividendos)
            price_series = data[["Close"]].rename(columns={"Close": ticker})
            price_series.to_csv(DIR_PRICES / f"{ticker}.csv")
            status, note, n_rows = "ok", "", len(data)
            print(f"OK  ({n_rows} dias)")

    except Exception as e:
        status, note, n_rows = "error", str(e)[:120], 0
        print(f"ERRO: {note}")

    # Salvar no relatório imediatamente (garante retomada mesmo com crash)
    new_row = pd.DataFrame([{
        "ticker":     ticker,
        "status":     status,
        "n_rows":     n_rows,
        "start_date": start_date,
        "end_date":   end_date,
        "note":       note,
    }])
    report_df    = pd.concat([report_df, new_row], ignore_index=True)
    report_df.to_csv(PATH_REPORT, index=False)
    already_done.add(ticker)

    time.sleep(DELAY_ENTRE_REQUESTS)

print("\nColeta concluída.")

[   1/725] A           2015-07-01 → 2025-12-31  OK  (2641 dias)
[   2/725] AABA        2015-07-01 → 2016-12-31

$AABA: possibly delisted; no timezone found

1 Failed download:
['AABA']: possibly delisted; no timezone found

DELISTED
[   3/725] AAL         2015-07-01 → 2024-06-30  OK  (2264 dias)
[   4/725] AAP         2015-07-01 → 2023-06-30  OK  (2013 dias)
[   5/725] AAPL        2015-07-01 → 2025-12-31  OK  (2641 dias)
[   6/725] ABBV        2015-07-01 → 2025-12-31  OK  (2641 dias)
[   7/725] ABC         2015-07-01 → 2023-06-30

$ABC: possibly delisted; no timezone found

1 Failed download:
['ABC']: possibly delisted; no timezone found

DELISTED
[   8/725] ABMD        2018-01-01 → 2022-06-30

$ABMD: possibly delisted; no timezone found

1 Failed download:
['ABMD']: possibly delisted; no timezone found

DELISTED
[   9/725] ABNB        2023-07-01 → 2025-12-31  OK  (627 dias)
[  10/725] ABT         2015-07-01 → 2025-12-31  OK  (2641 dias)
[  11/725] ACGL        2022-07-01 → 2025-12-31  OK  (878 dias)
[  12/725] ACN         2015-07-01 → 2025-12-31  OK  (2641 dias)
[  13/725] ADBE        2015-07-01 → 2025-12-31  OK  (2641 dias)
[  14/725] ADI         2015-07-01 → 2025-12-31  OK  (2641 dias)
[  15/725] ADM         2015-07-01 → 2025-12-31  OK  (2641 dias)
[  16/725] ADP         2015-07-01 → 2025-12-31  OK  (2641 dias)
[  17/725] ADS         2015-07-01 → 2019-12-31

$ADS: possibly delisted; no timezone found

1 Failed download:
['ADS']: possibly delisted; no timezone found

DELISTED
[  18/725] ADSK        2015-07-01 → 2025-12-31  OK  (2641 dias)
[  19/725] ADT         2015-07-01 → 2015-12-31

$ADT: possibly delisted; no price data found  (1d 2015-07-01 -> 2015-12-31) (Yahoo error = "Data doesn't exist for startDate = 1435723200, endDate = 1451538000")

1 Failed download:
['ADT']: possibly delisted; no price data found  (1d 2015-07-01 -> 2015-12-31) (Yahoo error = "Data doesn't exist for startDate = 1435723200, endDate = 1451538000")

DELISTED
[  20/725] AEE         2015-07-01 → 2025-12-31  OK  (2641 dias)
[  21/725] AEP         2015-07-01 → 2025-12-31  OK  (2641 dias)
[  22/725] AES         2015-07-01 → 2025-12-31  OK  (2641 dias)
[  23/725] AET         2015-07-01 → 2018-06-30  OK  (756 dias)
[  24/725] AFL         2015-07-01 → 2025-12-31  OK  (2641 dias)
[  25/725] AGN         2015-07-01 → 2019-12-31

$AGN: possibly delisted; no timezone found

1 Failed download:
['AGN']: possibly delisted; no timezone found

DELISTED
[  26/725] AIG         2015-07-01 → 2025-12-31  OK  (2641 dias)
[  27/725] AIV         2015-07-01 → 2020-06-30  OK  (1258 dias)
[  28/725] AIZ         2015-07-01 → 2025-12-31  OK  (2641 dias)
[  29/725] AJG         2016-01-01 → 2025-12-31  OK  (2513 dias)
[  30/725] AKAM        2015-07-01 → 2025-12-31  OK  (2641 dias)
[  31/725] ALB         2016-07-01 → 2025-12-31  OK  (2388 dias)
[  32/725] ALGN        2017-01-01 → 2025-12-31  OK  (2261 dias)
[  33/725] ALK         2016-01-01 → 2023-06-30  OK  (1885 dias)
[  34/725] ALL         2015-07-01 → 2025-12-31  OK  (2641 dias)
[  35/725] ALLE        2015-07-01 → 2025-12-31  OK  (2641 dias)
[  36/725] ALXN        2015-07-01 → 2021-06-30

$ALXN: possibly delisted; no timezone found

1 Failed download:
['ALXN']: possibly delisted; no timezone found

DELISTED
[  37/725] AMAT        2015-07-01 → 2025-12-31  OK  (2641 dias)
[  38/725] AMCR        2019-01-01 → 2025-12-31  OK  (1759 dias)
[  39/725] AMD         2017-01-01 → 2025-12-31  OK  (2261 dias)
[  40/725] AME         2015-07-01 → 2025-12-31  OK  (2641 dias)
[  41/725] AMG         2015-07-01 → 2019-06-30  OK  (1006 dias)
[  42/725] AMGN        2015-07-01 → 2025-12-31  OK  (2641 dias)
[  43/725] AMP         2015-07-01 → 2025-12-31  OK  (2641 dias)
[  44/725] AMT         2015-07-01 → 2025-12-31  OK  (2641 dias)
[  45/725] AMZN        2015-07-01 → 2025-12-31  OK  (2641 dias)
[  46/725] AN          2015-07-01 → 2017-06-30  OK  (504 dias)
[  47/725] ANDV        2015-07-01 → 2018-06-30  OK  (755 dias)
[  48/725] ANET        2018-07-01 → 2025-12-31  OK  (1885 dias)
[  49/725] ANSS        2017-01-01 → 2025-06-30

$ANSS: possibly delisted; no timezone found

1 Failed download:
['ANSS']: possibly delisted; no timezone found

DELISTED
[  50/725] ANTM        2015-07-01 → 2021-12-31

$ANTM: possibly delisted; no timezone found

1 Failed download:
['ANTM']: possibly delisted; no timezone found

DELISTED
[  51/725] AON         2015-07-01 → 2025-12-31  OK  (2641 dias)
[  52/725] AOS         2017-07-01 → 2025-12-31  OK  (2136 dias)
[  53/725] APA         2015-07-01 → 2025-12-31  OK  (2641 dias)
[  54/725] APC         2015-07-01 → 2019-06-30

$APC: possibly delisted; no price data found  (1d 2015-07-01 -> 2019-06-30) (Yahoo error = "Data doesn't exist for startDate = 1435723200, endDate = 1561867200")

1 Failed download:
['APC']: possibly delisted; no price data found  (1d 2015-07-01 -> 2019-06-30) (Yahoo error = "Data doesn't exist for startDate = 1435723200, endDate = 1561867200")

DELISTED
[  55/725] APD         2015-07-01 → 2025-12-31  OK  (2641 dias)
[  56/725] APH         2015-07-01 → 2025-12-31  OK  (2641 dias)
[  57/725] APO         2024-07-01 → 2025-12-31  OK  (377 dias)
[  58/725] APP         2025-07-01 → 2025-12-31  OK  (127 dias)
[  59/725] APTV        2015-07-01 → 2025-12-31  OK  (2641 dias)
[  60/725] ARE         2017-01-01 → 2025-12-31  OK  (2261 dias)
[  61/725] ARES        2025-07-01 → 2025-12-31  OK  (127 dias)
[  62/725] ARG         2015-07-01 → 2015-12-31

$ARG: possibly delisted; no price data found  (1d 2015-07-01 -> 2015-12-31) (Yahoo error = "Data doesn't exist for startDate = 1435723200, endDate = 1451538000")

1 Failed download:
['ARG']: possibly delisted; no price data found  (1d 2015-07-01 -> 2015-12-31) (Yahoo error = "Data doesn't exist for startDate = 1435723200, endDate = 1451538000")

DELISTED
[  63/725] ARNC        2015-07-01 → 2019-12-31

$ARNC: possibly delisted; no timezone found

1 Failed download:
['ARNC']: possibly delisted; no timezone found

DELISTED
[  64/725] ATO         2019-01-01 → 2025-12-31  OK  (1759 dias)
[  65/725] ATVI        2015-07-01 → 2023-06-30

$ATVI: possibly delisted; no timezone found

1 Failed download:
['ATVI']: possibly delisted; no timezone found

DELISTED
[  66/725] AVB         2015-07-01 → 2025-12-31  OK  (2641 dias)
[  67/725] AVGO        2015-07-01 → 2025-12-31  OK  (2641 dias)
[  68/725] AVY         2015-07-01 → 2025-12-31  OK  (2641 dias)
[  69/725] AWK         2016-01-01 → 2025-12-31  OK  (2513 dias)
[  70/725] AXON        2023-01-01 → 2025-12-31  OK  (751 dias)
[  71/725] AXP         2015-07-01 → 2025-12-31  OK  (2641 dias)
[  72/725] AYI         2016-01-01 → 2017-12-31  OK  (503 dias)
[  73/725] AZO         2015-07-01 → 2025-12-31  OK  (2641 dias)
[  74/725] BA          2015-07-01 → 2025-12-31  OK  (2641 dias)
[  75/725] BAC         2015-07-01 → 2025-12-31  OK  (2641 dias)
[  76/725] BALL        2022-01-01 → 2025-12-31  OK  (1002 dias)
[  77/725] BAX         2015-07-01 → 2025-12-31  OK  (2641 dias)
[  78/725] BBBY        2015-07-01 → 2017-06-30  OK  (504 dias)
[  79/725] BBT         2015-07-01 → 2019-06-30  OK  (1006 dias)
[  80/725] BBWI        2021-07-01 → 2024-06-30  OK  (753 dias)
[  81/725] BBY         2015-07-01 → 2025-12-31  OK  (2641 dias)
[  82/725] BCR         2015-07-01 → 2017-06-30

$BCR: possibly delisted; no price data found  (1d 2015-07-01 -> 2017-06-30)

1 Failed download:
['BCR']: possibly delisted; no price data found  (1d 2015-07-01 -> 2017-06-30)

DELISTED
[  83/725] BDX         2015-07-01 → 2025-12-31  OK  (2641 dias)
[  84/725] BEN         2015-07-01 → 2025-12-31  OK  (2641 dias)
[  85/725] BF.B        2015-07-01 → 2025-12-31

$BF.B: possibly delisted; no price data found  (1d 2015-07-01 -> 2025-12-31)

1 Failed download:
['BF.B']: possibly delisted; no price data found  (1d 2015-07-01 -> 2025-12-31)

DELISTED
[  86/725] BG          2023-01-01 → 2025-12-31  OK  (751 dias)
[  87/725] BHF         2017-07-01 → 2018-12-31  OK  (367 dias)
[  88/725] BHGE        2015-07-01 → 2019-06-30

$BHGE: possibly delisted; no timezone found

1 Failed download:
['BHGE']: possibly delisted; no timezone found

DELISTED
[  89/725] BIIB        2015-07-01 → 2025-12-31  OK  (2641 dias)
[  90/725] BIO         2020-01-01 → 2024-06-30  OK  (1130 dias)
[  91/725] BK          2015-07-01 → 2025-12-31  OK  (2641 dias)
[  92/725] BKNG        2015-07-01 → 2025-12-31  OK  (2641 dias)
[  93/725] BKR         2019-07-01 → 2025-12-31  OK  (1635 dias)
[  94/725] BLDR        2023-07-01 → 2025-12-31  OK  (627 dias)
[  95/725] BLK         2015-07-01 → 2025-12-31  OK  (2641 dias)
[  96/725] BLL         2015-07-01 → 2021-12-31

$BLL: possibly delisted; no timezone found

1 Failed download:
['BLL']: possibly delisted; no timezone found

DELISTED
[  97/725] BMY         2015-07-01 → 2025-12-31  OK  (2641 dias)
[  98/725] BR          2018-01-01 → 2025-12-31  OK  (2010 dias)
[  99/725] BRCM        2015-07-01 → 2015-12-31

$BRCM: possibly delisted; no price data found  (1d 2015-07-01 -> 2015-12-31)

1 Failed download:
['BRCM']: possibly delisted; no price data found  (1d 2015-07-01 -> 2015-12-31)

DELISTED
[ 100/725] BRK.B       2015-07-01 → 2025-12-31

$BRK.B: possibly delisted; no timezone found

1 Failed download:
['BRK.B']: possibly delisted; no timezone found

DELISTED
[ 101/725] BRO         2021-07-01 → 2025-12-31  OK  (1130 dias)
[ 102/725] BSX         2015-07-01 → 2025-12-31  OK  (2641 dias)
[ 103/725] BWA         2015-07-01 → 2024-12-31  OK  (2391 dias)
[ 104/725] BX          2023-07-01 → 2025-12-31  OK  (627 dias)
[ 105/725] BXLT        2015-07-01 → 2015-12-31

$BXLT: possibly delisted; no price data found  (1d 2015-07-01 -> 2015-12-31)

1 Failed download:
['BXLT']: possibly delisted; no price data found  (1d 2015-07-01 -> 2015-12-31)

DELISTED
[ 106/725] BXP         2015-07-01 → 2025-12-31  OK  (2641 dias)
[ 107/725] C           2015-07-01 → 2025-12-31  OK  (2641 dias)
[ 108/725] CA          2015-07-01 → 2018-06-30

$CA: possibly delisted; no price data found  (1d 2015-07-01 -> 2018-06-30) (Yahoo error = "Data doesn't exist for startDate = 1435723200, endDate = 1530331200")

1 Failed download:
['CA']: possibly delisted; no price data found  (1d 2015-07-01 -> 2018-06-30) (Yahoo error = "Data doesn't exist for startDate = 1435723200, endDate = 1530331200")

DELISTED
[ 109/725] CAG         2015-07-01 → 2025-12-31  OK  (2641 dias)
[ 110/725] CAH         2015-07-01 → 2025-12-31  OK  (2641 dias)
[ 111/725] CAM         2015-07-01 → 2015-12-31

$CAM: possibly delisted; no price data found  (1d 2015-07-01 -> 2015-12-31) (Yahoo error = "Data doesn't exist for startDate = 1435723200, endDate = 1451538000")

1 Failed download:
['CAM']: possibly delisted; no price data found  (1d 2015-07-01 -> 2015-12-31) (Yahoo error = "Data doesn't exist for startDate = 1435723200, endDate = 1451538000")

DELISTED
[ 112/725] CARR        2020-01-01 → 2025-12-31  OK  (1454 dias)
[ 113/725] CAT         2015-07-01 → 2025-12-31  OK  (2641 dias)
[ 114/725] CB          2015-07-01 → 2025-12-31  OK  (2641 dias)
[ 115/725] CBOE        2017-01-01 → 2025-12-31  OK  (2261 dias)
[ 116/725] CBRE        2015-07-01 → 2025-12-31  OK  (2641 dias)
[ 117/725] CBS         2015-07-01 → 2019-06-30

$CBS: possibly delisted; no timezone found

1 Failed download:
['CBS']: possibly delisted; no timezone found

DELISTED
[ 118/725] CCE         2015-07-01 → 2015-12-31

$CCE: possibly delisted; no price data found  (1d 2015-07-01 -> 2015-12-31)

1 Failed download:
['CCE']: possibly delisted; no price data found  (1d 2015-07-01 -> 2015-12-31)

DELISTED
[ 119/725] CCI         2015-07-01 → 2025-12-31  OK  (2641 dias)
[ 120/725] CCL         2015-07-01 → 2025-12-31  OK  (2641 dias)
[ 121/725] CDAY        2021-07-01 → 2023-12-31

$CDAY: possibly delisted; no timezone found

1 Failed download:
['CDAY']: possibly delisted; no timezone found

DELISTED
[ 122/725] CDNS        2017-07-01 → 2025-12-31  OK  (2136 dias)
[ 123/725] CDW         2019-07-01 → 2025-12-31  OK  (1635 dias)
[ 124/725] CE          2018-07-01 → 2024-12-31  OK  (1635 dias)
[ 125/725] CEG         2022-01-01 → 2025-12-31  OK  (991 dias)
[ 126/725] CELG        2015-07-01 → 2019-06-30

$CELG: possibly delisted; no timezone found

1 Failed download:
['CELG']: possibly delisted; no timezone found

DELISTED
[ 127/725] CERN        2015-07-01 → 2021-12-31

$CERN: possibly delisted; no timezone found

1 Failed download:
['CERN']: possibly delisted; no timezone found

DELISTED
[ 128/725] CF          2015-07-01 → 2025-12-31  OK  (2641 dias)
[ 129/725] CFG         2016-01-01 → 2025-12-31  OK  (2513 dias)
[ 130/725] CHD         2015-07-01 → 2025-12-31  OK  (2641 dias)
[ 131/725] CHK         2015-07-01 → 2017-12-31

$CHK: possibly delisted; no timezone found

1 Failed download:
['CHK']: possibly delisted; no timezone found

DELISTED
[ 132/725] CHRW        2015-07-01 → 2025-12-31  OK  (2641 dias)
[ 133/725] CHTR        2016-07-01 → 2025-12-31  OK  (2388 dias)
[ 134/725] CI          2015-07-01 → 2025-12-31  OK  (2641 dias)
[ 135/725] CINF        2015-07-01 → 2025-12-31  OK  (2641 dias)
[ 136/725] CL          2015-07-01 → 2025-12-31  OK  (2641 dias)
[ 137/725] CLX         2015-07-01 → 2025-12-31  OK  (2641 dias)
[ 138/725] CMA         2015-07-01 → 2023-12-31

$CMA: possibly delisted; no price data found  (1d 2015-07-01 -> 2023-12-31) (Yahoo error = "No data found, symbol may be delisted")

1 Failed download:
['CMA']: possibly delisted; no price data found  (1d 2015-07-01 -> 2023-12-31) (Yahoo error = "No data found, symbol may be delisted")

DELISTED
[ 139/725] CMCSA       2015-07-01 → 2025-12-31  OK  (2641 dias)
[ 140/725] CME         2015-07-01 → 2025-12-31  OK  (2641 dias)
[ 141/725] CMG         2015-07-01 → 2025-12-31  OK  (2641 dias)
[ 142/725] CMI         2015-07-01 → 2025-12-31  OK  (2641 dias)
[ 143/725] CMS         2015-07-01 → 2025-12-31  OK  (2641 dias)
[ 144/725] CNC         2016-01-01 → 2025-12-31  OK  (2513 dias)
[ 145/725] CNP         2015-07-01 → 2025-12-31  OK  (2641 dias)
[ 146/725] CNX         2015-07-01 → 2015-12-31  OK  (127 dias)
[ 147/725] COF         2015-07-01 → 2025-12-31  OK  (2641 dias)
[ 148/725] COG         2015-07-01 → 2021-06-30

$COG: possibly delisted; no timezone found

1 Failed download:
['COG']: possibly delisted; no timezone found

DELISTED
[ 149/725] COIN        2025-01-01 → 2025-12-31  OK  (249 dias)
[ 150/725] COL         2015-07-01 → 2018-06-30  OK  (741 dias)
[ 151/725] COO         2016-07-01 → 2025-12-31  OK  (2388 dias)
[ 152/725] COP         2015-07-01 → 2025-12-31  OK  (2641 dias)
[ 153/725] COR         2023-07-01 → 2025-12-31  OK  (627 dias)
[ 154/725] COST        2015-07-01 → 2025-12-31  OK  (2641 dias)
[ 155/725] COTY        2016-07-01 → 2020-06-30  OK  (1005 dias)
[ 156/725] CPAY        2024-01-01 → 2025-12-31  OK  (501 dias)
[ 157/725] CPB         2015-07-01 → 2025-12-31  OK  (2641 dias)
[ 158/725] CPGX        2015-07-01 → 2016-06-30

$CPGX: possibly delisted; no price data found  (1d 2015-07-01 -> 2016-06-30)

1 Failed download:
['CPGX']: possibly delisted; no price data found  (1d 2015-07-01 -> 2016-06-30)

DELISTED
[ 159/725] CPRI        2016-01-01 → 2019-12-31  OK  (1005 dias)
[ 160/725] CPRT        2018-07-01 → 2025-12-31  OK  (1885 dias)
[ 161/725] CPT         2022-01-01 → 2025-12-31  OK  (1002 dias)
[ 162/725] CRH         2025-07-01 → 2025-12-31  OK  (127 dias)
[ 163/725] CRL         2021-01-01 → 2025-12-31  OK  (1254 dias)
[ 164/725] CRM         2015-07-01 → 2025-12-31  OK  (2641 dias)
[ 165/725] CRWD        2024-01-01 → 2025-12-31  OK  (501 dias)
[ 166/725] CSCO        2015-07-01 → 2025-12-31  OK  (2641 dias)
[ 167/725] CSGP        2022-07-01 → 2025-12-31  OK  (878 dias)
[ 168/725] CSRA        2015-07-01 → 2017-12-31  OK  (535 dias)
[ 169/725] CSX         2015-07-01 → 2025-12-31  OK  (2641 dias)
[ 170/725] CTAS        2015-07-01 → 2025-12-31  OK  (2641 dias)
[ 171/725] CTL         2015-07-01 → 2020-06-30

$CTL: possibly delisted; no timezone found

1 Failed download:
['CTL']: possibly delisted; no timezone found

DELISTED
[ 172/725] CTLT        2020-07-01 → 2024-06-30

$CTLT: possibly delisted; no timezone found

1 Failed download:
['CTLT']: possibly delisted; no timezone found

DELISTED
[ 173/725] CTRA        2021-07-01 → 2025-12-31  OK  (1130 dias)
[ 174/725] CTSH        2015-07-01 → 2025-12-31  OK  (2641 dias)
[ 175/725] CTVA        2019-01-01 → 2025-12-31  OK  (1660 dias)
[ 176/725] CTXS        2015-07-01 → 2022-06-30

$CTXS: possibly delisted; no timezone found

1 Failed download:
['CTXS']: possibly delisted; no timezone found

DELISTED
[ 177/725] CVC         2015-07-01 → 2015-12-31

$CVC: possibly delisted; no price data found  (1d 2015-07-01 -> 2015-12-31)

1 Failed download:
['CVC']: possibly delisted; no price data found  (1d 2015-07-01 -> 2015-12-31)

DELISTED
[ 178/725] CVNA        2025-07-01 → 2025-12-31  OK  (127 dias)
[ 179/725] CVS         2015-07-01 → 2025-12-31  OK  (2641 dias)
[ 180/725] CVX         2015-07-01 → 2025-12-31  OK  (2641 dias)
[ 181/725] CXO         2016-01-01 → 2020-12-31

$CXO: possibly delisted; no timezone found

1 Failed download:
['CXO']: possibly delisted; no timezone found

DELISTED
[ 182/725] CZR         2021-01-01 → 2025-06-30  OK  (1126 dias)
[ 183/725] D           2015-07-01 → 2025-12-31  OK  (2641 dias)
[ 184/725] DAL         2015-07-01 → 2025-12-31  OK  (2641 dias)
[ 185/725] DASH        2025-01-01 → 2025-12-31  OK  (249 dias)
[ 186/725] DAY         2024-01-01 → 2025-12-31  OK  (501 dias)
[ 187/725] DD          2015-07-01 → 2025-12-31  OK  (2641 dias)
[ 188/725] DDOG        2025-07-01 → 2025-12-31  OK  (127 dias)
[ 189/725] DE          2015-07-01 → 2025-12-31  OK  (2641 dias)
[ 190/725] DECK        2024-01-01 → 2025-12-31  OK  (501 dias)
[ 191/725] DELL        2024-07-01 → 2025-12-31  OK  (377 dias)
[ 192/725] DFS         2015-07-01 → 2024-12-31

$DFS: possibly delisted; no timezone found

1 Failed download:
['DFS']: possibly delisted; no timezone found

DELISTED
[ 193/725] DG          2015-07-01 → 2025-12-31  OK  (2641 dias)
[ 194/725] DGX         2015-07-01 → 2025-12-31  OK  (2641 dias)
[ 195/725] DHI         2015-07-01 → 2025-12-31  OK  (2641 dias)
[ 196/725] DHR         2015-07-01 → 2025-12-31  OK  (2641 dias)
[ 197/725] DIS         2015-07-01 → 2025-12-31  OK  (2641 dias)
[ 198/725] DISCA       2015-07-01 → 2021-12-31

$DISCA: possibly delisted; no timezone found

1 Failed download:
['DISCA']: possibly delisted; no timezone found

DELISTED
[ 199/725] DISCK       2015-07-01 → 2021-12-31

$DISCK: possibly delisted; no timezone found

1 Failed download:
['DISCK']: possibly delisted; no timezone found

DELISTED
[ 200/725] DISH        2017-01-01 → 2022-12-31

$DISH: possibly delisted; no timezone found

1 Failed download:
['DISH']: possibly delisted; no timezone found

DELISTED
[ 201/725] DLR         2016-01-01 → 2025-12-31  OK  (2513 dias)
[ 202/725] DLTR        2015-07-01 → 2025-12-31  OK  (2641 dias)
[ 203/725] DNB         2015-07-01 → 2016-12-31

$DNB: possibly delisted; no timezone found

1 Failed download:
['DNB']: possibly delisted; no timezone found

DELISTED
[ 204/725] DO          2015-07-01 → 2016-06-30

$DO: possibly delisted; no timezone found

1 Failed download:
['DO']: possibly delisted; no timezone found

DELISTED
[ 205/725] DOC         2024-01-01 → 2025-12-31  OK  (501 dias)
[ 206/725] DOV         2015-07-01 → 2025-12-31  OK  (2641 dias)
[ 207/725] DOW         2015-07-01 → 2025-12-31  OK  (1706 dias)
[ 208/725] DPZ         2020-01-01 → 2025-12-31  OK  (1507 dias)
[ 209/725] DRE         2017-07-01 → 2022-06-30

$DRE: possibly delisted; no timezone found

1 Failed download:
['DRE']: possibly delisted; no timezone found

DELISTED
[ 210/725] DRI         2015-07-01 → 2025-12-31  OK  (2641 dias)
[ 211/725] DTE         2015-07-01 → 2025-12-31  OK  (2641 dias)
[ 212/725] DUK         2015-07-01 → 2025-12-31  OK  (2641 dias)
[ 213/725] DVA         2015-07-01 → 2025-12-31  OK  (2641 dias)
[ 214/725] DVN         2015-07-01 → 2025-12-31  OK  (2641 dias)
[ 215/725] DWDP        2017-07-01 → 2018-12-31

$DWDP: possibly delisted; no timezone found

1 Failed download:
['DWDP']: possibly delisted; no timezone found

DELISTED
[ 216/725] DXC         2017-01-01 → 2023-06-30  OK  (1633 dias)
[ 217/725] DXCM        2020-01-01 → 2025-12-31  OK  (1507 dias)
[ 218/725] EA          2015-07-01 → 2025-12-31  OK  (2641 dias)
[ 219/725] EBAY        2015-07-01 → 2025-12-31  OK  (2641 dias)
[ 220/725] ECL         2015-07-01 → 2025-12-31  OK  (2641 dias)
[ 221/725] ED          2015-07-01 → 2025-12-31  OK  (2641 dias)
[ 222/725] EFX         2015-07-01 → 2025-12-31  OK  (2641 dias)
[ 223/725] EG          2023-07-01 → 2025-12-31  OK  (627 dias)
[ 224/725] EIX         2015-07-01 → 2025-12-31  OK  (2641 dias)
[ 225/725] EL          2015-07-01 → 2025-12-31  OK  (2641 dias)
[ 226/725] ELV         2022-01-01 → 2025-12-31  OK  (1002 dias)
[ 227/725] EMC         2015-07-01 → 2016-06-30

$EMC: possibly delisted; no price data found  (1d 2015-07-01 -> 2016-06-30) (Yahoo error = "Data doesn't exist for startDate = 1435723200, endDate = 1467259200")

1 Failed download:
['EMC']: possibly delisted; no price data found  (1d 2015-07-01 -> 2016-06-30) (Yahoo error = "Data doesn't exist for startDate = 1435723200, endDate = 1467259200")

DELISTED
[ 228/725] EME         2025-07-01 → 2025-12-31  OK  (127 dias)
[ 229/725] EMN         2015-07-01 → 2025-06-30  OK  (2513 dias)
[ 230/725] EMR         2015-07-01 → 2025-12-31  OK  (2641 dias)
[ 231/725] ENDP        2015-07-01 → 2016-12-31

$ENDP: possibly delisted; no timezone found

1 Failed download:
['ENDP']: possibly delisted; no timezone found

DELISTED
[ 232/725] ENPH        2021-01-01 → 2025-06-30  OK  (1126 dias)
[ 233/725] EOG         2015-07-01 → 2025-12-31  OK  (2641 dias)
[ 234/725] EPAM        2021-07-01 → 2025-12-31  OK  (1130 dias)
[ 235/725] EQIX        2015-07-01 → 2025-12-31  OK  (2641 dias)
[ 236/725] EQR         2015-07-01 → 2025-12-31  OK  (2641 dias)
[ 237/725] EQT         2015-07-01 → 2025-12-31  OK  (2641 dias)
[ 238/725] ERIE        2024-07-01 → 2025-12-31  OK  (377 dias)
[ 239/725] ES          2015-07-01 → 2025-12-31  OK  (2641 dias)
[ 240/725] ESRX        2015-07-01 → 2018-06-30  OK  (755 dias)
[ 241/725] ESS         2015-07-01 → 2025-12-31  OK  (2641 dias)
[ 242/725] ESV         2015-07-01 → 2015-12-31

$ESV: possibly delisted; no timezone found

1 Failed download:
['ESV']: possibly delisted; no timezone found

DELISTED
[ 243/725] ETFC        2015-07-01 → 2020-06-30

$ETFC: possibly delisted; no timezone found

1 Failed download:
['ETFC']: possibly delisted; no timezone found

DELISTED
[ 244/725] ETN         2015-07-01 → 2025-12-31  OK  (2641 dias)
[ 245/725] ETR         2015-07-01 → 2025-12-31  OK  (2641 dias)
[ 246/725] ETSY        2020-07-01 → 2024-06-30  OK  (1005 dias)
[ 247/725] EVHC        2016-07-01 → 2018-06-30  OK  (502 dias)
[ 248/725] EVRG        2018-01-01 → 2025-12-31  OK  (2010 dias)
[ 249/725] EW          2015-07-01 → 2025-12-31  OK  (2641 dias)
[ 250/725] EXC         2015-07-01 → 2025-12-31  OK  (2641 dias)
[ 251/725] EXE         2025-01-01 → 2025-12-31  OK  (249 dias)
[ 252/725] EXPD        2015-07-01 → 2025-12-31  OK  (2641 dias)
[ 253/725] EXPE        2015-07-01 → 2025-12-31  OK  (2641 dias)
[ 254/725] EXR         2016-01-01 → 2025-12-31  OK  (2513 dias)
[ 255/725] F           2015-07-01 → 2025-12-31  OK  (2641 dias)
[ 256/725] FANG        2018-07-01 → 2025-12-31  OK  (1885 dias)
[ 257/725] FAST        2015-07-01 → 2025-12-31  OK  (2641 dias)
[ 258/725] FB          2015-07-01 → 2021-12-31

$FB: possibly delisted; no price data found  (1d 2015-07-01 -> 2021-12-31) (Yahoo error = "Data doesn't exist for startDate = 1435723200, endDate = 1640926800")

1 Failed download:
['FB']: possibly delisted; no price data found  (1d 2015-07-01 -> 2021-12-31) (Yahoo error = "Data doesn't exist for startDate = 1435723200, endDate = 1640926800")

DELISTED
[ 259/725] FBHS        2016-01-01 → 2022-06-30

$FBHS: possibly delisted; no timezone found

1 Failed download:
['FBHS']: possibly delisted; no timezone found

DELISTED
[ 260/725] FCX         2015-07-01 → 2025-12-31  OK  (2641 dias)
[ 261/725] FDS         2021-07-01 → 2025-12-31  OK  (1130 dias)
[ 262/725] FDX         2015-07-01 → 2025-12-31  OK  (2641 dias)
[ 263/725] FE          2015-07-01 → 2025-12-31  OK  (2641 dias)
[ 264/725] FFIV        2015-07-01 → 2025-12-31  OK  (2641 dias)
[ 265/725] FI          2023-01-01 → 2025-06-30

$FI: possibly delisted; no timezone found

1 Failed download:
['FI']: possibly delisted; no timezone found

DELISTED
[ 266/725] FICO        2023-01-01 → 2025-12-31  OK  (751 dias)
[ 267/725] FIS         2015-07-01 → 2025-12-31  OK  (2641 dias)
[ 268/725] FISV        2015-07-01 → 2025-12-31  OK  (2640 dias)
[ 269/725] FITB        2015-07-01 → 2025-12-31  OK  (2641 dias)
[ 270/725] FIX         2025-07-01 → 2025-12-31  OK  (127 dias)
[ 271/725] FL          2016-01-01 → 2019-06-30

$FL: possibly delisted; no timezone found

1 Failed download:
['FL']: possibly delisted; no timezone found

DELISTED
[ 272/725] FLIR        2015-07-01 → 2020-12-31

$FLIR: possibly delisted; no timezone found

1 Failed download:
['FLIR']: possibly delisted; no timezone found

DELISTED
[ 273/725] FLR         2015-07-01 → 2018-12-31  OK  (881 dias)
[ 274/725] FLS         2015-07-01 → 2020-12-31  OK  (1386 dias)
[ 275/725] FLT         2018-01-01 → 2023-12-31

$FLT: possibly delisted; no timezone found

1 Failed download:
['FLT']: possibly delisted; no timezone found

DELISTED
[ 276/725] FMC         2015-07-01 → 2024-12-31  OK  (2391 dias)
[ 277/725] FOSL        2015-07-01 → 2015-12-31  OK  (127 dias)
[ 278/725] FOX         2015-07-01 → 2025-12-31  OK  (1711 dias)
[ 279/725] FOXA        2015-07-01 → 2025-12-31  OK  (1712 dias)
[ 280/725] FRC         2019-01-01 → 2022-12-31

$FRC: possibly delisted; no timezone found

1 Failed download:
['FRC']: possibly delisted; no timezone found

DELISTED
[ 281/725] FRT         2016-01-01 → 2025-12-31  OK  (2513 dias)
[ 282/725] FSLR        2015-07-01 → 2025-12-31  OK  (2641 dias)
[ 283/725] FTI         2015-07-01 → 2020-12-31  OK  (1386 dias)
[ 284/725] FTNT        2018-07-01 → 2025-12-31  OK  (1885 dias)
[ 285/725] FTR         2015-07-01 → 2016-12-31

$FTR: possibly delisted; no timezone found

1 Failed download:
['FTR']: possibly delisted; no timezone found

DELISTED
[ 286/725] FTV         2016-07-01 → 2025-12-31  OK  (2387 dias)
[ 287/725] GAS         2015-07-01 → 2016-06-30

$GAS: possibly delisted; no price data found  (1d 2015-07-01 -> 2016-06-30)

1 Failed download:
['GAS']: possibly delisted; no price data found  (1d 2015-07-01 -> 2016-06-30)

DELISTED
[ 288/725] GD          2015-07-01 → 2025-12-31  OK  (2641 dias)
[ 289/725] GDDY        2024-01-01 → 2025-12-31  OK  (501 dias)
[ 290/725] GE          2015-07-01 → 2025-12-31  OK  (2641 dias)
[ 291/725] GEHC        2023-01-01 → 2025-12-31  OK  (751 dias)
[ 292/725] GEN         2022-07-01 → 2025-12-31  OK  (878 dias)
[ 293/725] GEV         2024-01-01 → 2025-12-31  OK  (442 dias)
[ 294/725] GGP         2015-07-01 → 2018-06-30

$GGP: possibly delisted; no price data found  (1d 2015-07-01 -> 2018-06-30)

1 Failed download:
['GGP']: possibly delisted; no price data found  (1d 2015-07-01 -> 2018-06-30)

DELISTED
[ 295/725] GILD        2015-07-01 → 2025-12-31  OK  (2641 dias)
[ 296/725] GIS         2015-07-01 → 2025-12-31  OK  (2641 dias)
[ 297/725] GL          2019-07-01 → 2025-12-31  OK  (1635 dias)
[ 298/725] GLW         2015-07-01 → 2025-12-31  OK  (2641 dias)
[ 299/725] GM          2015-07-01 → 2025-12-31  OK  (2641 dias)
[ 300/725] GMCR        2015-07-01 → 2015-12-31

$GMCR: possibly delisted; no price data found  (1d 2015-07-01 -> 2015-12-31)

1 Failed download:
['GMCR']: possibly delisted; no price data found  (1d 2015-07-01 -> 2015-12-31)

DELISTED
[ 301/725] GME         2015-07-01 → 2015-12-31  OK  (127 dias)
[ 302/725] GNRC        2021-01-01 → 2025-12-31  OK  (1254 dias)
[ 303/725] GOOG        2015-07-01 → 2025-12-31  OK  (2641 dias)
[ 304/725] GOOGL       2015-07-01 → 2025-12-31  OK  (2641 dias)
[ 305/725] GPC         2015-07-01 → 2025-12-31  OK  (2641 dias)
[ 306/725] GPN         2016-01-01 → 2025-12-31  OK  (2513 dias)
[ 307/725] GPS         2015-07-01 → 2021-12-31

$GPS: possibly delisted; no timezone found

1 Failed download:
['GPS']: possibly delisted; no timezone found

DELISTED
[ 308/725] GRMN        2015-07-01 → 2025-12-31  OK  (2641 dias)
[ 309/725] GS          2015-07-01 → 2025-12-31  OK  (2641 dias)
[ 310/725] GT          2015-07-01 → 2018-12-31  OK  (881 dias)
[ 311/725] GWW         2015-07-01 → 2025-12-31  OK  (2641 dias)
[ 312/725] HAL         2015-07-01 → 2025-12-31  OK  (2641 dias)
[ 313/725] HAR         2015-07-01 → 2016-12-31

1 Failed download:
['HAR']: TypeError("'NoneType' object is not subscriptable")

DELISTED
[ 314/725] HAS         2015-07-01 → 2025-12-31  OK  (2641 dias)
[ 315/725] HBAN        2015-07-01 → 2025-12-31  OK  (2641 dias)
[ 316/725] HBI         2015-07-01 → 2021-06-30

$HBI: possibly delisted; no timezone found

1 Failed download:
['HBI']: possibly delisted; no timezone found

DELISTED
[ 317/725] HCA         2015-07-01 → 2025-12-31  OK  (2641 dias)
[ 318/725] HCP         2015-07-01 → 2019-06-30

$HCP: possibly delisted; no timezone found

1 Failed download:
['HCP']: possibly delisted; no timezone found

DELISTED
[ 319/725] HD          2015-07-01 → 2025-12-31  OK  (2641 dias)
[ 320/725] HES         2015-07-01 → 2025-06-30

$HES: possibly delisted; no timezone found

1 Failed download:
['HES']: possibly delisted; no timezone found

DELISTED
[ 321/725] HFC         2018-01-01 → 2020-12-31

$HFC: possibly delisted; no timezone found

1 Failed download:
['HFC']: possibly delisted; no timezone found

DELISTED
[ 322/725] HIG         2015-07-01 → 2025-12-31  OK  (2641 dias)
[ 323/725] HII         2018-01-01 → 2025-12-31  OK  (2010 dias)
[ 324/725] HLT         2017-01-01 → 2025-12-31  OK  (2261 dias)
[ 325/725] HOG         2015-07-01 → 2019-12-31  OK  (1133 dias)
[ 326/725] HOLX        2016-01-01 → 2025-12-31  OK  (2513 dias)
[ 327/725] HON         2015-07-01 → 2025-12-31  OK  (2641 dias)
[ 328/725] HOOD        2025-07-01 → 2025-12-31  OK  (127 dias)
[ 329/725] HOT         2015-07-01 → 2016-06-30  OK  (199 dias)
[ 330/725] HP          2015-07-01 → 2019-12-31  OK  (1133 dias)
[ 331/725] HPE         2015-07-01 → 2025-12-31  OK  (2565 dias)
[ 332/725] HPQ         2015-07-01 → 2025-12-31  OK  (2641 dias)
[ 333/725] HRB         2015-07-01 → 2020-06-30  OK  (1258 dias)
[ 334/725] HRL         2015-07-01 → 2025-12-31  OK  (2641 dias)
[ 335/725] HRS         2015-07-01 → 2018-12-31

$HRS: possibly delisted; no timezone found

1 Failed download:
['HRS']: possibly delisted; no timezone found

DELISTED
[ 336/725] HSIC        2015-07-01 → 2025-12-31  OK  (2641 dias)
[ 337/725] HST         2015-07-01 → 2025-12-31  OK  (2641 dias)
[ 338/725] HSY         2015-07-01 → 2025-12-31  OK  (2641 dias)
[ 339/725] HUBB        2023-07-01 → 2025-12-31  OK  (627 dias)
[ 340/725] HUM         2015-07-01 → 2025-12-31  OK  (2641 dias)
[ 341/725] HWM         2020-01-01 → 2025-12-31  OK  (1507 dias)
[ 342/725] IBKR        2025-07-01 → 2025-12-31  OK  (127 dias)
[ 343/725] IBM         2015-07-01 → 2025-12-31  OK  (2641 dias)
[ 344/725] ICE         2015-07-01 → 2025-12-31  OK  (2641 dias)
[ 345/725] IDXX        2017-01-01 → 2025-12-31  OK  (2261 dias)
[ 346/725] IEX         2019-07-01 → 2025-12-31  OK  (1635 dias)
[ 347/725] IFF         2015-07-01 → 2025-12-31  OK  (2641 dias)
[ 348/725] ILMN        2015-07-01 → 2023-12-31  OK  (2140 dias)
[ 349/725] INCY        2017-01-01 → 2025-12-31  OK  (2261 dias)
[ 350/725] INFO        2017-01-01 → 2021-12-31

$INFO: possibly delisted; no price data found  (1d 2017-01-01 -> 2021-12-31) (Yahoo error = "Data doesn't exist for startDate = 1483246800, endDate = 1640926800")

1 Failed download:
['INFO']: possibly delisted; no price data found  (1d 2017-01-01 -> 2021-12-31) (Yahoo error = "Data doesn't exist for startDate = 1483246800, endDate = 1640926800")

DELISTED
[ 351/725] INTC        2015-07-01 → 2025-12-31  OK  (2641 dias)
[ 352/725] INTU        2015-07-01 → 2025-12-31  OK  (2641 dias)
[ 353/725] INVH        2022-07-01 → 2025-12-31  OK  (878 dias)
[ 354/725] IP          2015-07-01 → 2025-12-31  OK  (2641 dias)
[ 355/725] IPG         2015-07-01 → 2025-06-30

$IPG: possibly delisted; no timezone found

1 Failed download:
['IPG']: possibly delisted; no timezone found

DELISTED
[ 356/725] IPGP        2018-01-01 → 2021-12-31  OK  (1007 dias)
[ 357/725] IQV         2017-07-01 → 2025-12-31  OK  (2136 dias)
[ 358/725] IR          2015-07-01 → 2025-12-31  OK  (2171 dias)
[ 359/725] IRM         2015-07-01 → 2025-12-31

1 Failed download:
['IRM']: TypeError("'NoneType' object is not subscriptable")

DELISTED
[ 360/725] ISRG        2015-07-01 → 2025-12-31  OK  (2641 dias)
[ 361/725] IT          2017-01-01 → 2025-12-31  OK  (2261 dias)
[ 362/725] ITW         2015-07-01 → 2025-12-31  OK  (2641 dias)
[ 363/725] IVZ         2015-07-01 → 2025-12-31  OK  (2641 dias)
[ 364/725] J           2019-07-01 → 2025-12-31  OK  (1635 dias)
[ 365/725] JBHT        2015-07-01 → 2025-12-31  OK  (2641 dias)
[ 366/725] JBL         2023-07-01 → 2025-12-31  OK  (627 dias)
[ 367/725] JCI         2015-07-01 → 2025-12-31  OK  (2641 dias)
[ 368/725] JEC         2015-07-01 → 2019-06-30

$JEC: possibly delisted; no timezone found

1 Failed download:
['JEC']: possibly delisted; no timezone found

DELISTED
[ 369/725] JEF         2015-07-01 → 2019-06-30  OK  (1006 dias)
[ 370/725] JKHY        2018-07-01 → 2025-12-31  OK  (1885 dias)
[ 371/725] JNJ         2015-07-01 → 2025-12-31  OK  (2641 dias)
[ 372/725] JNPR        2015-07-01 → 2025-06-30

$JNPR: possibly delisted; no timezone found

1 Failed download:
['JNPR']: possibly delisted; no timezone found

DELISTED
[ 373/725] JPM         2015-07-01 → 2025-12-31  OK  (2641 dias)
[ 374/725] JWN         2015-07-01 → 2019-12-31

$JWN: possibly delisted; no timezone found

1 Failed download:
['JWN']: possibly delisted; no timezone found

DELISTED
[ 375/725] K           2015-07-01 → 2025-06-30

$K: possibly delisted; no timezone found

1 Failed download:
['K']: possibly delisted; no timezone found

DELISTED
[ 376/725] KDP         2015-07-01 → 2025-12-31  OK  (2641 dias)
[ 377/725] KEY         2015-07-01 → 2025-12-31  OK  (2641 dias)
[ 378/725] KEYS        2018-07-01 → 2025-12-31  OK  (1885 dias)
[ 379/725] KHC         2015-07-01 → 2025-12-31  OK  (2639 dias)
[ 380/725] KIM         2015-07-01 → 2025-12-31  OK  (2641 dias)
[ 381/725] KKR         2024-01-01 → 2025-12-31  OK  (501 dias)
[ 382/725] KLAC        2015-07-01 → 2025-12-31  OK  (2641 dias)
[ 383/725] KMB         2015-07-01 → 2025-12-31  OK  (2641 dias)
[ 384/725] KMI         2015-07-01 → 2025-12-31  OK  (2641 dias)
[ 385/725] KMX         2015-07-01 → 2025-06-30  OK  (2513 dias)
[ 386/725] KO          2015-07-01 → 2025-12-31  OK  (2641 dias)
[ 387/725] KORS        2015-07-01 → 2018-06-30

$KORS: possibly delisted; no price data found  (1d 2015-07-01 -> 2018-06-30)

1 Failed download:
['KORS']: possibly delisted; no price data found  (1d 2015-07-01 -> 2018-06-30)

DELISTED
[ 388/725] KR          2015-07-01 → 2025-12-31  OK  (2641 dias)
[ 389/725] KSS         2015-07-01 → 2020-06-30  OK  (1258 dias)
[ 390/725] KSU         2015-07-01 → 2021-06-30

$KSU: possibly delisted; no timezone found

1 Failed download:
['KSU']: possibly delisted; no timezone found

DELISTED
[ 391/725] KVUE        2023-07-01 → 2025-12-31  OK  (627 dias)
[ 392/725] L           2015-07-01 → 2025-12-31  OK  (2641 dias)
[ 393/725] LB          2015-07-01 → 2021-06-30

$LB: possibly delisted; no price data found  (1d 2015-07-01 -> 2021-06-30) (Yahoo error = "Data doesn't exist for startDate = 1435723200, endDate = 1625025600")

1 Failed download:
['LB']: possibly delisted; no price data found  (1d 2015-07-01 -> 2021-06-30) (Yahoo error = "Data doesn't exist for startDate = 1435723200, endDate = 1625025600")

DELISTED
[ 394/725] LDOS        2019-07-01 → 2025-12-31  OK  (1635 dias)
[ 395/725] LEG         2015-07-01 → 2021-06-30  OK  (1510 dias)
[ 396/725] LEN         2015-07-01 → 2025-12-31  OK  (2641 dias)
[ 397/725] LH          2015-07-01 → 2025-12-31  OK  (2641 dias)
[ 398/725] LHX         2019-01-01 → 2025-12-31  OK  (1759 dias)
[ 399/725] LII         2024-07-01 → 2025-12-31  OK  (377 dias)
[ 400/725] LIN         2018-07-01 → 2025-12-31  OK  (1885 dias)
[ 401/725] LKQ         2016-01-01 → 2025-06-30  OK  (2385 dias)
[ 402/725] LLL         2015-07-01 → 2019-06-30

$LLL: possibly delisted; no timezone found

1 Failed download:
['LLL']: possibly delisted; no timezone found

DELISTED
[ 403/725] LLTC        2015-07-01 → 2016-12-31

$LLTC: possibly delisted; no price data found  (1d 2015-07-01 -> 2016-12-31)

1 Failed download:
['LLTC']: possibly delisted; no price data found  (1d 2015-07-01 -> 2016-12-31)

DELISTED
[ 404/725] LLY         2015-07-01 → 2025-12-31  OK  (2641 dias)
[ 405/725] LM          2015-07-01 → 2016-06-30

$LM: possibly delisted; no timezone found

1 Failed download:
['LM']: possibly delisted; no timezone found

DELISTED
[ 406/725] LMT         2015-07-01 → 2025-12-31  OK  (2641 dias)
[ 407/725] LNC         2015-07-01 → 2023-06-30  OK  (2013 dias)
[ 408/725] LNT         2016-07-01 → 2025-12-31  OK  (2388 dias)
[ 409/725] LOW         2015-07-01 → 2025-12-31  OK  (2641 dias)
[ 410/725] LRCX        2015-07-01 → 2025-12-31  OK  (2641 dias)
[ 411/725] LULU        2023-07-01 → 2025-12-31  OK  (627 dias)
[ 412/725] LUMN        2020-07-01 → 2022-12-31  OK  (631 dias)
[ 413/725] LUV         2015-07-01 → 2025-12-31  OK  (2641 dias)
[ 414/725] LVLT        2015-07-01 → 2017-06-30

$LVLT: possibly delisted; no price data found  (1d 2015-07-01 -> 2017-06-30)

1 Failed download:
['LVLT']: possibly delisted; no price data found  (1d 2015-07-01 -> 2017-06-30)

DELISTED
[ 415/725] LVS         2019-07-01 → 2025-12-31  OK  (1635 dias)
[ 416/725] LW          2018-07-01 → 2025-12-31  OK  (1885 dias)
[ 417/725] LYB         2015-07-01 → 2025-12-31  OK  (2641 dias)
[ 418/725] LYV         2019-07-01 → 2025-12-31  OK  (1635 dias)
[ 419/725] M           2015-07-01 → 2019-12-31  OK  (1133 dias)
[ 420/725] MA          2015-07-01 → 2025-12-31  OK  (2641 dias)
[ 421/725] MAA         2016-07-01 → 2025-12-31  OK  (2388 dias)
[ 422/725] MAC         2015-07-01 → 2019-06-30  OK  (1006 dias)
[ 423/725] MAR         2015-07-01 → 2025-12-31  OK  (2641 dias)
[ 424/725] MAS         2015-07-01 → 2025-12-31  OK  (2641 dias)
[ 425/725] MAT         2015-07-01 → 2018-12-31  OK  (881 dias)
[ 426/725] MCD         2015-07-01 → 2025-12-31  OK  (2641 dias)
[ 427/725] MCHP        2015-07-01 → 2025-12-31  OK  (2641 dias)
[ 428/725] MCK         2015-07-01 → 2025-12-31  OK  (2641 dias)
[ 429/725] MCO         2015-07-01 → 2025-12-31  OK  (2641 dias)
[ 430/725] MDLZ        2015-07-01 → 2025-12-31  OK  (2641 dias)
[ 431/725] MDT         2015-07-01 → 2025-12-31  OK  (2641 dias)
[ 432/725] MET         2015-07-01 → 2025-12-31  OK  (2641 dias)
[ 433/725] META        2022-01-01 → 2025-12-31  OK  (1002 dias)
[ 434/725] MGM         2017-07-01 → 2025-12-31  OK  (2136 dias)
[ 435/725] MHK         2015-07-01 → 2025-06-30  OK  (2513 dias)
[ 436/725] MJN         2015-07-01 → 2016-12-31

$MJN: possibly delisted; no price data found  (1d 2015-07-01 -> 2016-12-31)

1 Failed download:
['MJN']: possibly delisted; no price data found  (1d 2015-07-01 -> 2016-12-31)

DELISTED
[ 437/725] MKC         2015-07-01 → 2025-12-31  OK  (2641 dias)
[ 438/725] MKTX        2019-07-01 → 2025-06-30  OK  (1507 dias)
[ 439/725] MLM         2015-07-01 → 2025-12-31  OK  (2641 dias)
[ 440/725] MMC         2015-07-01 → 2025-12-31

$MMC: possibly delisted; no timezone found

1 Failed download:
['MMC']: possibly delisted; no timezone found

DELISTED
[ 441/725] MMM         2015-07-01 → 2025-12-31  OK  (2641 dias)
[ 442/725] MNK         2015-07-01 → 2017-06-30

$MNK: possibly delisted; no timezone found

1 Failed download:
['MNK']: possibly delisted; no timezone found

DELISTED
[ 443/725] MNST        2015-07-01 → 2025-12-31  OK  (2641 dias)
[ 444/725] MO          2015-07-01 → 2025-12-31  OK  (2641 dias)
[ 445/725] MOH         2022-01-01 → 2025-12-31  OK  (1002 dias)
[ 446/725] MON         2015-07-01 → 2017-12-31

$MON: possibly delisted; no timezone found

1 Failed download:
['MON']: possibly delisted; no timezone found

DELISTED
[ 447/725] MOS         2015-07-01 → 2025-12-31  OK  (2641 dias)
[ 448/725] MPC         2015-07-01 → 2025-12-31  OK  (2641 dias)
[ 449/725] MPWR        2021-01-01 → 2025-12-31  OK  (1254 dias)
[ 450/725] MRK         2015-07-01 → 2025-12-31  OK  (2641 dias)
[ 451/725] MRNA        2021-07-01 → 2025-12-31  OK  (1130 dias)
[ 452/725] MRO         2015-07-01 → 2024-06-30

$MRO: possibly delisted; no timezone found

1 Failed download:
['MRO']: possibly delisted; no timezone found

DELISTED
[ 453/725] MS          2015-07-01 → 2025-12-31  OK  (2641 dias)
[ 454/725] MSCI        2018-01-01 → 2025-12-31  OK  (2010 dias)
[ 455/725] MSFT        2015-07-01 → 2025-12-31  OK  (2641 dias)
[ 456/725] MSI         2015-07-01 → 2025-12-31  OK  (2641 dias)
[ 457/725] MTB         2015-07-01 → 2025-12-31  OK  (2641 dias)
[ 458/725] MTCH        2021-07-01 → 2025-12-31  OK  (1130 dias)
[ 459/725] MTD         2016-07-01 → 2025-12-31  OK  (2388 dias)
[ 460/725] MU          2015-07-01 → 2025-12-31  OK  (2641 dias)
[ 461/725] MUR         2015-07-01 → 2017-06-30  OK  (504 dias)
[ 462/725] MXIM        2018-07-01 → 2021-06-30

$MXIM: possibly delisted; no timezone found

1 Failed download:
['MXIM']: possibly delisted; no timezone found

DELISTED
[ 463/725] MYL         2015-07-01 → 2020-06-30

$MYL: possibly delisted; no timezone found

1 Failed download:
['MYL']: possibly delisted; no timezone found

DELISTED
[ 464/725] NAVI        2015-07-01 → 2017-12-31  OK  (631 dias)
[ 465/725] NBL         2015-07-01 → 2020-06-30

$NBL: possibly delisted; no timezone found

1 Failed download:
['NBL']: possibly delisted; no timezone found

DELISTED
[ 466/725] NCLH        2017-07-01 → 2025-12-31  OK  (2136 dias)
[ 467/725] NDAQ        2015-07-01 → 2025-12-31  OK  (2641 dias)
[ 468/725] NDSN        2022-01-01 → 2025-12-31  OK  (1002 dias)
[ 469/725] NEE         2015-07-01 → 2025-12-31  OK  (2641 dias)
[ 470/725] NEM         2015-07-01 → 2025-12-31  OK  (2641 dias)
[ 471/725] NFLX        2015-07-01 → 2025-12-31  OK  (2641 dias)
[ 472/725] NFX         2015-07-01 → 2018-12-31  OK  (880 dias)
[ 473/725] NI          2015-07-01 → 2025-12-31  OK  (2641 dias)
[ 474/725] NKE         2015-07-01 → 2025-12-31  OK  (2641 dias)
[ 475/725] NKTR        2018-01-01 → 2019-06-30  OK  (375 dias)
[ 476/725] NLOK        2019-07-01 → 2022-06-30

$NLOK: possibly delisted; no timezone found

1 Failed download:
['NLOK']: possibly delisted; no timezone found

DELISTED
[ 477/725] NLSN        2015-07-01 → 2022-06-30

$NLSN: possibly delisted; no timezone found

1 Failed download:
['NLSN']: possibly delisted; no timezone found

DELISTED
[ 478/725] NOC         2015-07-01 → 2025-12-31  OK  (2641 dias)
[ 479/725] NOV         2015-07-01 → 2021-06-30  OK  (1510 dias)
[ 480/725] NOW         2019-07-01 → 2025-12-31  OK  (1635 dias)
[ 481/725] NRG         2015-07-01 → 2025-12-31  OK  (2641 dias)
[ 482/725] NSC         2015-07-01 → 2025-12-31  OK  (2641 dias)
[ 483/725] NTAP        2015-07-01 → 2025-12-31  OK  (2641 dias)
[ 484/725] NTRS        2015-07-01 → 2025-12-31  OK  (2641 dias)
[ 485/725] NUE         2015-07-01 → 2025-12-31  OK  (2641 dias)
[ 486/725] NVDA        2015-07-01 → 2025-12-31  OK  (2641 dias)
[ 487/725] NVR         2019-07-01 → 2025-12-31  OK  (1635 dias)
[ 488/725] NWL         2015-07-01 → 2023-06-30  OK  (2013 dias)
[ 489/725] NWS         2015-07-01 → 2025-12-31  OK  (2641 dias)
[ 490/725] NWSA        2015-07-01 → 2025-12-31  OK  (2641 dias)
[ 491/725] NXPI        2021-01-01 → 2025-12-31  OK  (1254 dias)
[ 492/725] O           2015-07-01 → 2025-12-31  OK  (2641 dias)
[ 493/725] ODFL        2019-07-01 → 2025-12-31  OK  (1635 dias)
[ 494/725] OGN         2021-01-01 → 2023-06-30  OK  (535 dias)
[ 495/725] OI          2015-07-01 → 2016-06-30  OK  (252 dias)
[ 496/725] OKE         2015-07-01 → 2025-12-31  OK  (2641 dias)
[ 497/725] OMC         2015-07-01 → 2025-12-31  OK  (2641 dias)
[ 498/725] ON          2022-01-01 → 2025-12-31  OK  (1002 dias)
[ 499/725] ORCL        2015-07-01 → 2025-12-31  OK  (2641 dias)
[ 500/725] ORLY        2015-07-01 → 2025-12-31  OK  (2641 dias)
[ 501/725] OTIS        2020-01-01 → 2025-12-31  OK  (1454 dias)
[ 502/725] OXY         2015-07-01 → 2025-12-31  OK  (2641 dias)
[ 503/725] PANW        2023-01-01 → 2025-12-31  OK  (751 dias)
[ 504/725] PARA        2022-01-01 → 2025-06-30

$PARA: possibly delisted; no timezone found

1 Failed download:
['PARA']: possibly delisted; no timezone found

DELISTED
[ 505/725] PAYC        2020-01-01 → 2025-12-31  OK  (1507 dias)
[ 506/725] PAYX        2015-07-01 → 2025-12-31  OK  (2641 dias)
[ 507/725] PBCT        2015-07-01 → 2021-12-31

$PBCT: possibly delisted; no timezone found

1 Failed download:
['PBCT']: possibly delisted; no timezone found

DELISTED
[ 508/725] PBI         2015-07-01 → 2016-12-31  OK  (380 dias)
[ 509/725] PCAR        2015-07-01 → 2025-12-31  OK  (2641 dias)
[ 510/725] PCG         2015-07-01 → 2025-12-31  OK  (2641 dias)
[ 511/725] PCL         2015-07-01 → 2015-12-31

1 Failed download:
['PCL']: TypeError("'NoneType' object is not subscriptable")

DELISTED
[ 512/725] PCP         2015-07-01 → 2015-12-31

$PCP: possibly delisted; no price data found  (1d 2015-07-01 -> 2015-12-31) (Yahoo error = "Data doesn't exist for startDate = 1435723200, endDate = 1451538000")

1 Failed download:
['PCP']: possibly delisted; no price data found  (1d 2015-07-01 -> 2015-12-31) (Yahoo error = "Data doesn't exist for startDate = 1435723200, endDate = 1451538000")

DELISTED
[ 513/725] PDCO        2015-07-01 → 2017-12-31

$PDCO: possibly delisted; no timezone found

1 Failed download:
['PDCO']: possibly delisted; no timezone found

DELISTED
[ 514/725] PEAK        2019-07-01 → 2023-12-31

$PEAK: possibly delisted; no timezone found

1 Failed download:
['PEAK']: possibly delisted; no timezone found

DELISTED
[ 515/725] PEG         2015-07-01 → 2025-12-31  OK  (2641 dias)
[ 516/725] PENN        2021-01-01 → 2022-06-30  OK  (375 dias)
[ 517/725] PEP         2015-07-01 → 2025-12-31  OK  (2641 dias)
[ 518/725] PFE         2015-07-01 → 2025-12-31  OK  (2641 dias)
[ 519/725] PFG         2015-07-01 → 2025-12-31  OK  (2641 dias)
[ 520/725] PG          2015-07-01 → 2025-12-31  OK  (2641 dias)
[ 521/725] PGR         2015-07-01 → 2025-12-31  OK  (2641 dias)
[ 522/725] PH          2015-07-01 → 2025-12-31  OK  (2641 dias)
[ 523/725] PHM         2015-07-01 → 2025-12-31  OK  (2641 dias)
[ 524/725] PKG         2017-07-01 → 2025-12-31  OK  (2136 dias)
[ 525/725] PKI         2015-07-01 → 2022-12-31

$PKI: possibly delisted; no timezone found

1 Failed download:
['PKI']: possibly delisted; no timezone found

DELISTED
[ 526/725] PLD         2015-07-01 → 2025-12-31  OK  (2641 dias)
[ 527/725] PLTR        2024-07-01 → 2025-12-31  OK  (377 dias)
[ 528/725] PM          2015-07-01 → 2025-12-31  OK  (2641 dias)
[ 529/725] PNC         2015-07-01 → 2025-12-31  OK  (2641 dias)
[ 530/725] PNR         2015-07-01 → 2025-12-31  OK  (2641 dias)
[ 531/725] PNW         2015-07-01 → 2025-12-31  OK  (2641 dias)
[ 532/725] PODD        2023-01-01 → 2025-12-31  OK  (751 dias)
[ 533/725] POM         2015-07-01 → 2015-12-31

$POM: possibly delisted; no price data found  (1d 2015-07-01 -> 2015-12-31) (Yahoo error = "Data doesn't exist for startDate = 1435723200, endDate = 1451538000")

1 Failed download:
['POM']: possibly delisted; no price data found  (1d 2015-07-01 -> 2015-12-31) (Yahoo error = "Data doesn't exist for startDate = 1435723200, endDate = 1451538000")

DELISTED
[ 534/725] POOL        2020-07-01 → 2025-12-31  OK  (1382 dias)
[ 535/725] PPG         2015-07-01 → 2025-12-31  OK  (2641 dias)
[ 536/725] PPL         2015-07-01 → 2025-12-31  OK  (2641 dias)
[ 537/725] PRGO        2015-07-01 → 2021-06-30  OK  (1510 dias)
[ 538/725] PRU         2015-07-01 → 2025-12-31  OK  (2641 dias)
[ 539/725] PSA         2015-07-01 → 2025-12-31  OK  (2641 dias)
[ 540/725] PSKY        2025-07-01 → 2025-12-31  OK  (127 dias)
[ 541/725] PSX         2015-07-01 → 2025-12-31  OK  (2641 dias)
[ 542/725] PTC         2021-01-01 → 2025-12-31  OK  (1254 dias)
[ 543/725] PVH         2015-07-01 → 2022-06-30  OK  (1762 dias)
[ 544/725] PWR         2015-07-01 → 2025-12-31  OK  (2641 dias)
[ 545/725] PX          2015-07-01 → 2018-06-30

$PX: possibly delisted; no price data found  (1d 2015-07-01 -> 2018-06-30) (Yahoo error = "Data doesn't exist for startDate = 1435723200, endDate = 1530331200")

1 Failed download:
['PX']: possibly delisted; no price data found  (1d 2015-07-01 -> 2018-06-30) (Yahoo error = "Data doesn't exist for startDate = 1435723200, endDate = 1530331200")

DELISTED
[ 546/725] PXD         2015-07-01 → 2023-12-31

$PXD: possibly delisted; no timezone found

1 Failed download:
['PXD']: possibly delisted; no timezone found

DELISTED
[ 547/725] PYPL        2015-07-01 → 2025-12-31  OK  (2639 dias)
[ 548/725] Q           2025-07-01 → 2025-12-31  OK  (45 dias)
[ 549/725] QCOM        2015-07-01 → 2025-12-31  OK  (2641 dias)
[ 550/725] QRVO        2015-07-01 → 2024-06-30  OK  (2264 dias)
[ 551/725] R           2015-07-01 → 2016-12-31  OK  (380 dias)
[ 552/725] RAI         2015-07-01 → 2017-06-30

$RAI: possibly delisted; no price data found  (1d 2015-07-01 -> 2017-06-30)

1 Failed download:
['RAI']: possibly delisted; no price data found  (1d 2015-07-01 -> 2017-06-30)

DELISTED
[ 553/725] RCL         2015-07-01 → 2025-12-31  OK  (2641 dias)
[ 554/725] RE          2017-01-01 → 2023-06-30

$RE: possibly delisted; no timezone found

1 Failed download:
['RE']: possibly delisted; no timezone found

DELISTED
[ 555/725] REG         2017-01-01 → 2025-12-31  OK  (2261 dias)
[ 556/725] REGN        2015-07-01 → 2025-12-31  OK  (2641 dias)
[ 557/725] RF          2015-07-01 → 2025-12-31  OK  (2641 dias)
[ 558/725] RHI         2015-07-01 → 2023-12-31  OK  (2140 dias)
[ 559/725] RHT         2015-07-01 → 2019-06-30

$RHT: possibly delisted; no timezone found

1 Failed download:
['RHT']: possibly delisted; no timezone found

DELISTED
[ 560/725] RIG         2015-07-01 → 2017-06-30  OK  (504 dias)
[ 561/725] RJF         2017-01-01 → 2025-12-31  OK  (2261 dias)
[ 562/725] RL          2015-07-01 → 2025-12-31  OK  (2641 dias)
[ 563/725] RMD         2017-07-01 → 2025-12-31  OK  (2136 dias)
[ 564/725] ROK         2015-07-01 → 2025-12-31  OK  (2641 dias)
[ 565/725] ROL         2018-07-01 → 2025-12-31  OK  (1885 dias)
[ 566/725] ROP         2015-07-01 → 2025-12-31  OK  (2641 dias)
[ 567/725] ROST        2015-07-01 → 2025-12-31  OK  (2641 dias)
[ 568/725] RRC         2015-07-01 → 2017-12-31  OK  (631 dias)
[ 569/725] RSG         2015-07-01 → 2025-12-31  OK  (2641 dias)
[ 570/725] RTN         2015-07-01 → 2019-12-31

$RTN: possibly delisted; no timezone found

1 Failed download:
['RTN']: possibly delisted; no timezone found

DELISTED
[ 571/725] RTX         2020-01-01 → 2025-12-31  OK  (1507 dias)
[ 572/725] RVTY        2023-01-01 → 2025-12-31  OK  (751 dias)
[ 573/725] SBAC        2017-07-01 → 2025-12-31  OK  (2136 dias)
[ 574/725] SBNY        2021-07-01 → 2022-12-31

$SBNY: possibly delisted; no price data found  (1d 2021-07-01 -> 2022-12-31) (Yahoo error = "Data doesn't exist for startDate = 1625112000, endDate = 1672462800")

1 Failed download:
['SBNY']: possibly delisted; no price data found  (1d 2021-07-01 -> 2022-12-31) (Yahoo error = "Data doesn't exist for startDate = 1625112000, endDate = 1672462800")

DELISTED
[ 575/725] SBUX        2015-07-01 → 2025-12-31  OK  (2641 dias)
[ 576/725] SCG         2015-07-01 → 2018-12-31  OK  (871 dias)
[ 577/725] SCHW        2015-07-01 → 2025-12-31  OK  (2641 dias)
[ 578/725] SE          2015-07-01 → 2016-12-31

$SE: possibly delisted; no price data found  (1d 2015-07-01 -> 2016-12-31) (Yahoo error = "Data doesn't exist for startDate = 1435723200, endDate = 1483160400")

1 Failed download:
['SE']: possibly delisted; no price data found  (1d 2015-07-01 -> 2016-12-31) (Yahoo error = "Data doesn't exist for startDate = 1435723200, endDate = 1483160400")

DELISTED
[ 579/725] SEDG        2021-07-01 → 2023-06-30  OK  (502 dias)
[ 580/725] SEE         2015-07-01 → 2023-06-30  OK  (2013 dias)
[ 581/725] SHW         2015-07-01 → 2025-12-31  OK  (2641 dias)
[ 582/725] SIG         2015-07-01 → 2017-12-31  OK  (631 dias)
[ 583/725] SIVB        2018-01-01 → 2022-12-31

$SIVB: possibly delisted; no timezone found

1 Failed download:
['SIVB']: possibly delisted; no timezone found

DELISTED
[ 584/725] SJM         2015-07-01 → 2025-12-31  OK  (2641 dias)
[ 585/725] SLB         2015-07-01 → 2025-12-31  OK  (2641 dias)
[ 586/725] SLG         2015-07-01 → 2020-12-31  OK  (1386 dias)
[ 587/725] SMCI        2024-01-01 → 2025-12-31  OK  (501 dias)
[ 588/725] SNA         2015-07-01 → 2025-12-31  OK  (2641 dias)
[ 589/725] SNDK        2015-07-01 → 2025-12-31  OK  (221 dias)
[ 590/725] SNI         2015-07-01 → 2017-12-31

$SNI: possibly delisted; no price data found  (1d 2015-07-01 -> 2017-12-31)

1 Failed download:
['SNI']: possibly delisted; no price data found  (1d 2015-07-01 -> 2017-12-31)

DELISTED
[ 591/725] SNPS        2017-01-01 → 2025-12-31  OK  (2261 dias)
[ 592/725] SO          2015-07-01 → 2025-12-31  OK  (2641 dias)
[ 593/725] SOLV        2024-01-01 → 2025-12-31  OK  (443 dias)
[ 594/725] SPG         2015-07-01 → 2025-12-31  OK  (2641 dias)
[ 595/725] SPGI        2015-07-01 → 2025-12-31  OK  (2641 dias)
[ 596/725] SPLS        2015-07-01 → 2017-06-30

$SPLS: possibly delisted; no price data found  (1d 2015-07-01 -> 2017-06-30) (Yahoo error = "Data doesn't exist for startDate = 1435723200, endDate = 1498795200")

1 Failed download:
['SPLS']: possibly delisted; no price data found  (1d 2015-07-01 -> 2017-06-30) (Yahoo error = "Data doesn't exist for startDate = 1435723200, endDate = 1498795200")

DELISTED
[ 597/725] SRCL        2015-07-01 → 2018-06-30

$SRCL: possibly delisted; no price data found  (1d 2015-07-01 -> 2018-06-30)

1 Failed download:
['SRCL']: possibly delisted; no price data found  (1d 2015-07-01 -> 2018-06-30)

DELISTED
[ 598/725] SRE         2015-07-01 → 2025-12-31  OK  (2641 dias)
[ 599/725] STE         2019-07-01 → 2025-12-31  OK  (1635 dias)
[ 600/725] STI         2015-07-01 → 2019-06-30

$STI: possibly delisted; no price data found  (1d 2015-07-01 -> 2019-06-30) (Yahoo error = "Data doesn't exist for startDate = 1435723200, endDate = 1561867200")

1 Failed download:
['STI']: possibly delisted; no price data found  (1d 2015-07-01 -> 2019-06-30) (Yahoo error = "Data doesn't exist for startDate = 1435723200, endDate = 1561867200")

DELISTED
[ 601/725] STJ         2015-07-01 → 2016-12-31

$STJ: possibly delisted; no price data found  (1d 2015-07-01 -> 2016-12-31)

1 Failed download:
['STJ']: possibly delisted; no price data found  (1d 2015-07-01 -> 2016-12-31)

DELISTED
[ 602/725] STLD        2022-07-01 → 2025-12-31  OK  (878 dias)
[ 603/725] STT         2015-07-01 → 2025-12-31  OK  (2641 dias)
[ 604/725] STX         2015-07-01 → 2025-12-31  OK  (2641 dias)
[ 605/725] STZ         2015-07-01 → 2025-12-31  OK  (2641 dias)
[ 606/725] SW          2024-07-01 → 2025-12-31  OK  (377 dias)
[ 607/725] SWK         2015-07-01 → 2025-12-31  OK  (2641 dias)
[ 608/725] SWKS        2015-07-01 → 2025-12-31  OK  (2641 dias)
[ 609/725] SWN         2015-07-01 → 2016-12-31

$SWN: possibly delisted; no timezone found

1 Failed download:
['SWN']: possibly delisted; no timezone found

DELISTED
[ 610/725] SYF         2015-07-01 → 2025-12-31  OK  (2641 dias)
[ 611/725] SYK         2015-07-01 → 2025-12-31  OK  (2641 dias)
[ 612/725] SYMC        2015-07-01 → 2019-06-30

$SYMC: possibly delisted; no timezone found

1 Failed download:
['SYMC']: possibly delisted; no timezone found

DELISTED
[ 613/725] SYY         2015-07-01 → 2025-12-31  OK  (2641 dias)
[ 614/725] T           2015-07-01 → 2025-12-31  OK  (2641 dias)
[ 615/725] TAP         2015-07-01 → 2025-12-31  OK  (2641 dias)
[ 616/725] TDC         2015-07-01 → 2016-12-31  OK  (380 dias)
[ 617/725] TDG         2016-01-01 → 2025-12-31  OK  (2513 dias)
[ 618/725] TDY         2020-01-01 → 2025-12-31  OK  (1507 dias)
[ 619/725] TE          2015-07-01 → 2016-06-30

$TE: possibly delisted; no price data found  (1d 2015-07-01 -> 2016-06-30) (Yahoo error = "Data doesn't exist for startDate = 1435723200, endDate = 1467259200")

1 Failed download:
['TE']: possibly delisted; no price data found  (1d 2015-07-01 -> 2016-06-30) (Yahoo error = "Data doesn't exist for startDate = 1435723200, endDate = 1467259200")

DELISTED
[ 620/725] TECH        2021-07-01 → 2025-12-31  OK  (1130 dias)
[ 621/725] TEL         2015-07-01 → 2025-12-31  OK  (2641 dias)
[ 622/725] TER         2020-07-01 → 2025-12-31  OK  (1382 dias)
[ 623/725] TFC         2019-07-01 → 2025-12-31  OK  (1635 dias)
[ 624/725] TFX         2019-01-01 → 2024-12-31  OK  (1509 dias)
[ 625/725] TGNA        2015-07-01 → 2016-12-31  OK  (380 dias)
[ 626/725] TGT         2015-07-01 → 2025-12-31  OK  (2641 dias)
[ 627/725] THC         2015-07-01 → 2015-12-31  OK  (127 dias)
[ 628/725] TIF         2015-07-01 → 2020-12-31

$TIF: possibly delisted; no timezone found

1 Failed download:
['TIF']: possibly delisted; no timezone found

DELISTED
[ 629/725] TJX         2015-07-01 → 2025-12-31  OK  (2641 dias)
[ 630/725] TKO         2025-01-01 → 2025-12-31  OK  (249 dias)
[ 631/725] TMK         2015-07-01 → 2019-06-30

$TMK: possibly delisted; no timezone found

1 Failed download:
['TMK']: possibly delisted; no timezone found

DELISTED
[ 632/725] TMO         2015-07-01 → 2025-12-31  OK  (2641 dias)
[ 633/725] TMUS        2019-07-01 → 2025-12-31  OK  (1635 dias)
[ 634/725] TPL         2024-07-01 → 2025-12-31  OK  (377 dias)
[ 635/725] TPR         2015-07-01 → 2025-12-31  OK  (2641 dias)
[ 636/725] TRGP        2022-07-01 → 2025-12-31  OK  (878 dias)
[ 637/725] TRIP        2015-07-01 → 2019-06-30  OK  (1006 dias)
[ 638/725] TRMB        2021-01-01 → 2025-12-31  OK  (1254 dias)
[ 639/725] TROW        2015-07-01 → 2025-12-31  OK  (2641 dias)
[ 640/725] TRV         2015-07-01 → 2025-12-31  OK  (2641 dias)
[ 641/725] TSCO        2015-07-01 → 2025-12-31  OK  (2641 dias)
[ 642/725] TSLA        2020-07-01 → 2025-12-31  OK  (1382 dias)
[ 643/725] TSN         2015-07-01 → 2025-12-31  OK  (2641 dias)
[ 644/725] TSS         2015-07-01 → 2019-06-30

$TSS: possibly delisted; no timezone found

1 Failed download:
['TSS']: possibly delisted; no timezone found

DELISTED
[ 645/725] TT          2020-01-01 → 2025-12-31  OK  (1507 dias)
[ 646/725] TTD         2025-07-01 → 2025-12-31  OK  (127 dias)
[ 647/725] TTWO        2018-01-01 → 2025-12-31  OK  (2010 dias)
[ 648/725] TWC         2015-07-01 → 2015-12-31

$TWC: possibly delisted; no price data found  (1d 2015-07-01 -> 2015-12-31)

1 Failed download:
['TWC']: possibly delisted; no price data found  (1d 2015-07-01 -> 2015-12-31)

DELISTED
[ 649/725] TWTR        2018-01-01 → 2022-06-30

$TWTR: possibly delisted; no timezone found

1 Failed download:
['TWTR']: possibly delisted; no timezone found

DELISTED
[ 650/725] TWX         2015-07-01 → 2017-12-31  OK  (630 dias)
[ 651/725] TXN         2015-07-01 → 2025-12-31  OK  (2641 dias)
[ 652/725] TXT         2015-07-01 → 2025-12-31  OK  (2641 dias)
[ 653/725] TYL         2020-01-01 → 2025-12-31  OK  (1507 dias)
[ 654/725] UA          2016-01-01 → 2021-12-31  OK  (1455 dias)
[ 655/725] UAA         2015-07-01 → 2021-12-31  OK  (1638 dias)
[ 656/725] UAL         2015-07-01 → 2025-12-31  OK  (2641 dias)
[ 657/725] UBER        2023-07-01 → 2025-12-31  OK  (627 dias)
[ 658/725] UDR         2016-01-01 → 2025-12-31  OK  (2513 dias)
[ 659/725] UHS         2015-07-01 → 2025-12-31  OK  (2641 dias)
[ 660/725] ULTA        2016-01-01 → 2025-12-31  OK  (2513 dias)
[ 661/725] UNH         2015-07-01 → 2025-12-31  OK  (2641 dias)
[ 662/725] UNM         2015-07-01 → 2021-06-30  OK  (1510 dias)
[ 663/725] UNP         2015-07-01 → 2025-12-31  OK  (2641 dias)
[ 664/725] UPS         2015-07-01 → 2025-12-31  OK  (2641 dias)
[ 665/725] URBN        2015-07-01 → 2016-12-31  OK  (380 dias)
[ 666/725] URI         2015-07-01 → 2025-12-31  OK  (2641 dias)
[ 667/725] USB         2015-07-01 → 2025-12-31  OK  (2641 dias)
[ 668/725] UTX         2015-07-01 → 2019-12-31

$UTX: possibly delisted; no timezone found

1 Failed download:
['UTX']: possibly delisted; no timezone found

DELISTED
[ 669/725] V           2015-07-01 → 2025-12-31  OK  (2641 dias)
[ 670/725] VAR         2015-07-01 → 2020-12-31

$VAR: possibly delisted; no timezone found

1 Failed download:
['VAR']: possibly delisted; no timezone found

DELISTED
[ 671/725] VFC         2015-07-01 → 2023-12-31  OK  (2140 dias)
[ 672/725] VIAB        2015-07-01 → 2019-06-30

$VIAB: possibly delisted; no timezone found

1 Failed download:
['VIAB']: possibly delisted; no timezone found

DELISTED
[ 673/725] VIAC        2019-07-01 → 2021-12-31

$VIAC: possibly delisted; no timezone found

1 Failed download:
['VIAC']: possibly delisted; no timezone found

DELISTED
[ 674/725] VICI        2022-01-01 → 2025-12-31  OK  (1002 dias)
[ 675/725] VLO         2015-07-01 → 2025-12-31  OK  (2641 dias)
[ 676/725] VLTO        2023-07-01 → 2025-12-31  OK  (562 dias)
[ 677/725] VMC         2015-07-01 → 2025-12-31  OK  (2641 dias)
[ 678/725] VNO         2015-07-01 → 2022-12-31  OK  (1890 dias)
[ 679/725] VNT         2020-07-01 → 2020-12-31  OK  (68 dias)
[ 680/725] VRSK        2015-07-01 → 2025-12-31  OK  (2641 dias)
[ 681/725] VRSN        2015-07-01 → 2025-12-31  OK  (2641 dias)
[ 682/725] VRTX        2015-07-01 → 2025-12-31  OK  (2641 dias)
[ 683/725] VST         2024-01-01 → 2025-12-31  OK  (501 dias)
[ 684/725] VTR         2015-07-01 → 2025-12-31  OK  (2641 dias)
[ 685/725] VTRS        2020-07-01 → 2025-12-31  OK  (1382 dias)
[ 686/725] VZ          2015-07-01 → 2025-12-31  OK  (2641 dias)
[ 687/725] WAB         2019-01-01 → 2025-12-31  OK  (1759 dias)
[ 688/725] WAT         2015-07-01 → 2025-12-31  OK  (2641 dias)
[ 689/725] WBA         2015-07-01 → 2025-06-30

$WBA: possibly delisted; no timezone found

1 Failed download:
['WBA']: possibly delisted; no timezone found

DELISTED
[ 690/725] WBD         2022-01-01 → 2025-12-31  OK  (1002 dias)
[ 691/725] WCG         2018-07-01 → 2019-12-31

$WCG: possibly delisted; no timezone found

1 Failed download:
['WCG']: possibly delisted; no timezone found

DELISTED
[ 692/725] WDAY        2024-07-01 → 2025-12-31  OK  (377 dias)
[ 693/725] WDC         2015-07-01 → 2025-12-31  OK  (2641 dias)
[ 694/725] WEC         2015-07-01 → 2025-12-31  OK  (2641 dias)
[ 695/725] WELL        2015-07-01 → 2025-12-31  OK  (2641 dias)
[ 696/725] WFC         2015-07-01 → 2025-12-31  OK  (2641 dias)
[ 697/725] WFM         2015-07-01 → 2017-06-30

$WFM: possibly delisted; no price data found  (1d 2015-07-01 -> 2017-06-30)

1 Failed download:
['WFM']: possibly delisted; no price data found  (1d 2015-07-01 -> 2017-06-30)

DELISTED
[ 698/725] WHR         2015-07-01 → 2023-12-31  OK  (2140 dias)
[ 699/725] WLTW        2016-01-01 → 2021-12-31

$WLTW: possibly delisted; no timezone found

1 Failed download:
['WLTW']: possibly delisted; no timezone found

DELISTED
[ 700/725] WM          2015-07-01 → 2025-12-31  OK  (2641 dias)
[ 701/725] WMB         2015-07-01 → 2025-12-31  OK  (2641 dias)
[ 702/725] WMT         2015-07-01 → 2025-12-31  OK  (2641 dias)
[ 703/725] WRB         2019-07-01 → 2025-12-31  OK  (1635 dias)
[ 704/725] WRK         2015-07-01 → 2024-06-30

$WRK: possibly delisted; no timezone found

1 Failed download:
['WRK']: possibly delisted; no timezone found

DELISTED
[ 705/725] WSM         2025-01-01 → 2025-12-31  OK  (249 dias)
[ 706/725] WST         2020-01-01 → 2025-12-31  OK  (1507 dias)
[ 707/725] WTW         2022-01-01 → 2025-12-31  OK  (1002 dias)
[ 708/725] WU          2015-07-01 → 2021-06-30  OK  (1510 dias)
[ 709/725] WY          2015-07-01 → 2025-12-31  OK  (2641 dias)
[ 710/725] WYND        2015-07-01 → 2017-12-31

$WYND: possibly delisted; no timezone found

1 Failed download:
['WYND']: possibly delisted; no timezone found

DELISTED
[ 711/725] WYNN        2015-07-01 → 2025-12-31  OK  (2641 dias)
[ 712/725] XEC         2015-07-01 → 2019-12-31

$XEC: possibly delisted; no timezone found

1 Failed download:
['XEC']: possibly delisted; no timezone found

DELISTED
[ 713/725] XEL         2015-07-01 → 2025-12-31  OK  (2641 dias)
[ 714/725] XL          2015-07-01 → 2018-06-30

$XL: possibly delisted; no timezone found

1 Failed download:
['XL']: possibly delisted; no timezone found

DELISTED
[ 715/725] XLNX        2015-07-01 → 2021-12-31

$XLNX: possibly delisted; no timezone found

1 Failed download:
['XLNX']: possibly delisted; no timezone found

DELISTED
[ 716/725] XOM         2015-07-01 → 2025-12-31  OK  (2641 dias)
[ 717/725] XRAY        2015-07-01 → 2023-12-31  OK  (2140 dias)
[ 718/725] XRX         2015-07-01 → 2020-12-31  OK  (1386 dias)
[ 719/725] XYL         2015-07-01 → 2025-12-31  OK  (2641 dias)
[ 720/725] XYZ         2025-07-01 → 2025-12-31  OK  (127 dias)
[ 721/725] YUM         2015-07-01 → 2025-12-31  OK  (2641 dias)
[ 722/725] ZBH         2015-07-01 → 2025-12-31  OK  (2641 dias)
[ 723/725] ZBRA        2019-07-01 → 2025-12-31  OK  (1635 dias)
[ 724/725] ZION        2015-07-01 → 2023-12-31  OK  (2140 dias)
[ 725/725] ZTS         2015-07-01 → 2025-12-31  OK  (2641 dias)

Coleta concluída.

In [98]:
# ── Sumário final da coleta ───────────────────────────────────────────────────
report_df = pd.read_csv(PATH_REPORT)

contagem = report_df["status"].value_counts()
print("=== SUMÁRIO DA COLETA ===")
print(f"  ✅ OK (dados baixados):    {contagem.get('ok', 0)}")
print(f"  ⚠️  Delisted/sem dados:   {contagem.get('delisted', 0)}")
print(f"  ❌ Erros:                 {contagem.get('error', 0)}")
print(f"  Total:                    {len(report_df)}")
print()

# Listar tickers delisted para busca em fontes alternativas (Tiingo / EODHD)
delisted = report_df[report_df["status"] == "delisted"]
if len(delisted) > 0:
    tickers_df = pd.read_csv(PATH_TICKERS)
    print(f"Tickers delisted ({len(delisted)}) — buscar no Tiingo ou EODHD:")
    for _, r in delisted.iterrows():
        t_info = tickers_df[tickers_df["ticker"] == r["ticker"]]
        if len(t_info) > 0:
            t = t_info.iloc[0]
            print(f"  {r['ticker']:10s}  {t['first_period']} → {t['last_period']}")

=== SUMÁRIO DA COLETA ===
  ✅ OK (dados baixados):    592
  ⚠️  Delisted/sem dados:   133
  ❌ Erros:                 0
  Total:                    725

Tickers delisted (133) — buscar no Tiingo ou EODHD:
  AABA        2015/S2 → 2016/S2
  ABC         2015/S2 → 2023/S1
  ABMD        2018/S1 → 2022/S1
  ADS         2015/S2 → 2019/S2
  ADT         2015/S2 → 2015/S2
  AGN         2015/S2 → 2019/S2
  ALXN        2015/S2 → 2021/S1
  ANSS        2017/S1 → 2025/S1
  ANTM        2015/S2 → 2021/S2
  APC         2015/S2 → 2019/S1
  ARG         2015/S2 → 2015/S2
  ARNC        2015/S2 → 2019/S2
  ATVI        2015/S2 → 2023/S1
  BCR         2015/S2 → 2017/S1
  BF.B        2015/S2 → 2025/S2
  BHGE        2015/S2 → 2019/S1
  BLL         2015/S2 → 2021/S2
  BRCM        2015/S2 → 2015/S2
  BRK.B       2015/S2 → 2025/S2
  BXLT        2015/S2 → 2015/S2
  CA          2015/S2 → 2018/S1
  CAM         2015/S2 → 2015/S2
  CBS         2015/S2 → 2019/S1
  CCE         2015/S2 → 2015/S2
  CDAY        2021/S2 → 2023/S2
  CELG        2015/S2 → 2019/S1
  CERN        2015/S2 → 2021/S2
  CHK         2015/S2 → 2017/S2
  CMA         2015/S2 → 2023/S2
  COG         2015/S2 → 2021/S1
  CPGX        2015/S2 → 2016/S1
  CTL         2015/S2 → 2020/S1
  CTLT        2020/S2 → 2024/S1
  CTXS        2015/S2 → 2022/S1
  CVC         2015/S2 → 2015/S2
  CXO         2016/S1 → 2020/S2
  DFS         2015/S2 → 2024/S2
  DISCA       2015/S2 → 2021/S2
  DISCK       2015/S2 → 2021/S2
  DISH        2017/S1 → 2022/S2
  DNB         2015/S2 → 2016/S2
  DO          2015/S2 → 2016/S1
  DRE         2017/S2 → 2022/S1
  DWDP        2017/S2 → 2018/S2
  EMC         2015/S2 → 2016/S1
  ENDP        2015/S2 → 2016/S2
  ESV         2015/S2 → 2015/S2
  ETFC        2015/S2 → 2020/S1
  FB          2015/S2 → 2021/S2
  FBHS        2016/S1 → 2022/S1
  FI          2023/S1 → 2025/S1
  FL          2016/S1 → 2019/S1
  FLIR        2015/S2 → 2020/S2
  FLT         2018/S1 → 2023/S2
  FRC         2019/S1 → 2022/S2
  FTR         2015/S2 → 2016/S2
  GAS         2015/S2 → 2016/S1
  GGP         2015/S2 → 2018/S1
  GMCR        2015/S2 → 2015/S2
  GPS         2015/S2 → 2021/S2
  HAR         2015/S2 → 2016/S2
  HBI         2015/S2 → 2021/S1
  HCP         2015/S2 → 2019/S1
  HES         2015/S2 → 2025/S1
  HFC         2018/S1 → 2020/S2
  HRS         2015/S2 → 2018/S2
  INFO        2017/S1 → 2021/S2
  IPG         2015/S2 → 2025/S1
  IRM         2015/S2 → 2025/S2
  JEC         2015/S2 → 2019/S1
  JNPR        2015/S2 → 2025/S1
  JWN         2015/S2 → 2019/S2
  K           2015/S2 → 2025/S1
  KORS        2015/S2 → 2018/S1
  KSU         2015/S2 → 2021/S1
  LB          2015/S2 → 2021/S1
  LLL         2015/S2 → 2019/S1
  LLTC        2015/S2 → 2016/S2
  LM          2015/S2 → 2016/S1
  LVLT        2015/S2 → 2017/S1
  MJN         2015/S2 → 2016/S2
  MMC         2015/S2 → 2025/S2
  MNK         2015/S2 → 2017/S1
  MON         2015/S2 → 2017/S2
  MRO         2015/S2 → 2024/S1
  MXIM        2018/S2 → 2021/S1
  MYL         2015/S2 → 2020/S1
  NBL         2015/S2 → 2020/S1
  NLOK        2019/S2 → 2022/S1
  NLSN        2015/S2 → 2022/S1
  PARA        2022/S1 → 2025/S1
  PBCT        2015/S2 → 2021/S2
  PCL         2015/S2 → 2015/S2
  PCP         2015/S2 → 2015/S2
  PDCO        2015/S2 → 2017/S2
  PEAK        2019/S2 → 2023/S2
  PKI         2015/S2 → 2022/S2
  POM         2015/S2 → 2015/S2
  PX          2015/S2 → 2018/S1
  PXD         2015/S2 → 2023/S2
  RAI         2015/S2 → 2017/S1
  RE          2017/S1 → 2023/S1
  RHT         2015/S2 → 2019/S1
  RTN         2015/S2 → 2019/S2
  SBNY        2021/S2 → 2022/S2
  SE          2015/S2 → 2016/S2
  SIVB        2018/S1 → 2022/S2
  SNI         2015/S2 → 2017/S2
  SPLS        2015/S2 → 2017/S1
  SRCL        2015/S2 → 2018/S1
  STI         2015/S2 → 2019/S1
  STJ         2015/S2 → 2016/S2
  SWN         2015/S2 → 2016/S2
  SYMC        2015/S2 → 2019/S1
  TE          2015/S2 → 2016/S1
  TIF         2015/S2 → 2020/S2
  TMK         2015/S2 → 2019/S1
  TSS         2015/S2 → 2019/S1
  TWC         2015/S2 → 2015/S2
  TWTR        2018/S1 → 2022/S1
  UTX         2015/S2 → 2019/S2
  VAR         2015/S2 → 2020/S2
  VIAB        2015/S2 → 2019/S1
  VIAC        2019/S2 → 2021/S2
  WBA         2015/S2 → 2025/S1
  WCG         2018/S2 → 2019/S2
  WFM         2015/S2 → 2017/S1
  WLTW        2016/S1 → 2021/S2
  WRK         2015/S2 → 2024/S1
  WYND        2015/S2 → 2017/S2
  XEC         2015/S2 → 2019/S2
  XL          2015/S2 → 2018/S1
  XLNX        2015/S2 → 2021/S2

In [99]:
delisted

    ticker    status  n_rows  start_date    end_date                note
1     AABA  delisted       0  2015-07-01  2016-12-31  sem dados no Yahoo
6      ABC  delisted       0  2015-07-01  2023-06-30  sem dados no Yahoo
7     ABMD  delisted       0  2018-01-01  2022-06-30  sem dados no Yahoo
16     ADS  delisted       0  2015-07-01  2019-12-31  sem dados no Yahoo
18     ADT  delisted       0  2015-07-01  2015-12-31  sem dados no Yahoo
..     ...       ...     ...         ...         ...                 ...
703    WRK  delisted       0  2015-07-01  2024-06-30  sem dados no Yahoo
709   WYND  delisted       0  2015-07-01  2017-12-31  sem dados no Yahoo
711    XEC  delisted       0  2015-07-01  2019-12-31  sem dados no Yahoo
713     XL  delisted       0  2015-07-01  2018-06-30  sem dados no Yahoo
714   XLNX  delisted       0  2015-07-01  2021-12-31  sem dados no Yahoo

[133 rows x 6 columns]

In [100]:
report_df

    ticker    status  n_rows  start_date    end_date                note
0        A        ok    2641  2015-07-01  2025-12-31                 NaN
1     AABA  delisted       0  2015-07-01  2016-12-31  sem dados no Yahoo
2      AAL        ok    2264  2015-07-01  2024-06-30                 NaN
3      AAP        ok    2013  2015-07-01  2023-06-30                 NaN
4     AAPL        ok    2641  2015-07-01  2025-12-31                 NaN
..     ...       ...     ...         ...         ...                 ...
720    YUM        ok    2641  2015-07-01  2025-12-31                 NaN
721    ZBH        ok    2641  2015-07-01  2025-12-31                 NaN
722   ZBRA        ok    1635  2019-07-01  2025-12-31                 NaN
723   ZION        ok    2140  2015-07-01  2023-12-31                 NaN
724    ZTS        ok    2641  2015-07-01  2025-12-31                 NaN

[725 rows x 6 columns]

In [ ]:
#tiingo API token: dadfd331f2cb44969b8f7468006d20ad62b13262

Plano de recuperação dos 133 delisted
Os 133 se dividem em quatro grupos com estratégias diferentes:
Tipo 1 — Problema de formato (2 tickers) → Yahoo, só mudar o ticker
BF.B e BRK.B usam ponto, mas o Yahoo usa hífen: BF-B e BRK-B. Resolve com um retry simples.
Tipo 2 — Renomeação de ticker (10 tickers) → Yahoo com novo ticker + concatenar
A empresa existe, só o ticker mudou. Ex: FB → META, ANTM → ELV, CTL → LUMN. Busca no Yahoo com o novo nome e junta o histórico antigo com o novo.
Tipo 3 — Adquiridas/fundidas (37 tickers) → Tiingo
O ticker sumiu do Yahoo porque a empresa foi absorvida. O Tiingo mantém histórico de tickers delistados. Ex: CELG (adquirida BMS), XLNX (adquirida AMD), TWTR (privatizada).
Tipo 4 — Falências reais (7 tickers) → Tiingo
SIVB, FRC, SBNY (bancos de 2023), ENDP, MNK etc. O Tiingo tem o histórico até a data da falência, que é exatamente o que precisamos.
Não mapeados (77 tickers) → Tiingo como fallback geral para todos que o Yahoo não entrega.

In [102]:
import requests
headers = {
    'Content-Type': 'application/json'
}
requestResponse = requests.get("https://api.tiingo.com/tiingo/daily/aaba/prices?startDate=2015-07-02&token=dadfd331f2cb44969b8f7468006d20ad62b13262&resampleFreq=daily", headers=headers)
print(requestResponse.json())

[{'date': '2015-07-02T00:00:00.000Z', 'close': 39.38, 'high': 39.64, 'low': 39.19, 'open': 39.26, 'volume': 7712994, 'adjClose': 10.8196563864, 'adjHigh': 10.8910913956, 'adjLow': 10.7674538797, 'adjOpen': 10.7866863822, 'adjVolume': 7712994, 'divCash': 0.0, 'splitFactor': 1.0}, {'date': '2015-07-06T00:00:00.000Z', 'close': 38.61, 'high': 39.12, 'low': 38.46, 'open': 38.76, 'volume': 11803417, 'adjClose': 10.6080988593, 'adjHigh': 10.7482213773, 'adjLow': 10.566886354, 'adjOpen': 10.6493113646, 'adjVolume': 11803417, 'divCash': 0.0, 'splitFactor': 1.0}, {'date': '2015-07-07T00:00:00.000Z', 'close': 38.23, 'high': 38.38, 'low': 36.575, 'open': 38.24, 'volume': 19432474, 'adjClose': 10.5036938459, 'adjHigh': 10.5449063512, 'adjLow': 10.0489825377, 'adjOpen': 10.5064413463, 'adjVolume': 19432474, 'divCash': 0.0, 'splitFactor': 1.0}, {'date': '2015-07-08T00:00:00.000Z', 'close': 37.23, 'high': 37.49, 'low': 36.94, 'open': 37.2, 'volume': 20529176, 'adjClose': 10.2289438107, 'adjHigh': 10.3003788199, 'adjLow': 10.1492663005, 'adjOpen': 10.2207013097, 'adjVolume': 20529176, 'divCash': 0.0, 'splitFactor': 1.0}, {'date': '2015-07-09T00:00:00.000Z', 'close': 37.61, 'high': 38.68, 'low': 37.52, 'open': 38.23, 'volume': 16909387, 'adjClose': 10.3333488241, 'adjHigh': 10.6273313618, 'adjLow': 10.3086213209, 'adjOpen': 10.5036938459, 'adjVolume': 16909387, 'divCash': 0.0, 'splitFactor': 1.0}, {'date': '2015-07-10T00:00:00.000Z', 'close': 37.92, 'high': 38.42, 'low': 37.61, 'open': 38.35, 'volume': 10057576, 'adjClose': 10.418521335, 'adjHigh': 10.5558963526, 'adjLow': 10.3333488241, 'adjOpen': 10.5366638502, 'adjVolume': 10057576, 'divCash': 0.0, 'splitFactor': 1.0}, {'date': '2015-07-13T00:00:00.000Z', 'close': 38.76, 'high': 38.8, 'low': 38.1, 'open': 38.25, 'volume': 8713178, 'adjClose': 10.6493113646, 'adjHigh': 10.660301366, 'adjLow': 10.4679763414, 'adjOpen': 10.5091888466, 'adjVolume': 8713178, 'divCash': 0.0, 'splitFactor': 1.0}, {'date': '2015-07-14T00:00:00.000Z', 'close': 38.63, 'high': 39.03, 'low': 38.44, 'open': 38.65, 'volume': 9506509, 'adjClose': 10.61359386, 'adjHigh': 10.7234938741, 'adjLow': 10.5613913533, 'adjOpen': 10.6190888607, 'adjVolume': 9506509, 'divCash': 0.0, 'splitFactor': 1.0}, {'date': '2015-07-15T00:00:00.000Z', 'close': 38.38, 'high': 38.8, 'low': 38.15, 'open': 38.51, 'volume': 9147265, 'adjClose': 10.5449063512, 'adjHigh': 10.660301366, 'adjLow': 10.4817138431, 'adjOpen': 10.5806238558, 'adjVolume': 9147265, 'divCash': 0.0, 'splitFactor': 1.0}, {'date': '2015-07-16T00:00:00.000Z', 'close': 38.91, 'high': 38.96, 'low': 38.6, 'open': 38.7, 'volume': 8462417, 'adjClose': 10.6905238699, 'adjHigh': 10.7042613716, 'adjLow': 10.605351359, 'adjOpen': 10.6328263625, 'adjVolume': 8462417, 'divCash': 0.0, 'splitFactor': 1.0}, {'date': '2015-07-17T00:00:00.000Z', 'close': 39.68, 'high': 39.79, 'low': 38.93, 'open': 39.19, 'volume': 14864268, 'adjClose': 10.902081397, 'adjHigh': 10.9323039009, 'adjLow': 10.6960188706, 'adjOpen': 10.7674538797, 'adjVolume': 14864268, 'divCash': 0.0, 'splitFactor': 1.0}, {'date': '2015-07-20T00:00:00.000Z', 'close': 39.54, 'high': 39.98, 'low': 39.26, 'open': 39.98, 'volume': 14752071, 'adjClose': 10.8636163921, 'adjHigh': 10.9845064075, 'adjLow': 10.7866863822, 'adjOpen': 10.9845064075, 'adjVolume': 14752071, 'divCash': 0.0, 'splitFactor': 1.0}, {'date': '2015-07-21T00:00:00.000Z', 'close': 39.73, 'high': 39.85, 'low': 39.355, 'open': 39.61, 'volume': 14861571, 'adjClose': 10.9158188987, 'adjHigh': 10.948788903, 'adjLow': 10.8127876355, 'adjOpen': 10.8828488945, 'adjVolume': 14861571, 'divCash': 0.0, 'splitFactor': 1.0}, {'date': '2015-07-22T00:00:00.000Z', 'close': 39.24, 'high': 39.63, 'low': 38.26, 'open': 38.57, 'volume': 17714798, 'adjClose': 10.7811913815, 'adjHigh': 10.8883438952, 'adjLow': 10.511936347, 'adjOpen': 10.5971088579, 'adjVolume': 17714798, 'divCash': 0.0, 'splitFactor': 1.0}, {'date': '2015-07-23T00:00:00.000Z', 'close': 39.21, 'high': 39.785, 'low': 39.06, 'open': 39.3, 'volume': 9267432, 'adjClose': 10.7729488804, 'adjHigh': 10.9309301507, 'adjLow': 10.7317363752, 'adjOpen': 10.7976763836, 'adjVolume': 9267432, 'divCash': 0.0, 'splitFactor': 1.0}, {'date': '2015-07-24T00:00:00.000Z', 'close': 38.85, 'high': 39.58, 'low': 38.67, 'open': 39.58, 'volume': 8590731, 'adjClose': 10.6740388678, 'adjHigh': 10.8746063935, 'adjLow': 10.6245838614, 'adjOpen': 10.8746063935, 'adjVolume': 8590731, 'divCash': 0.0, 'splitFactor': 1.0}, {'date': '2015-07-27T00:00:00.000Z', 'close': 37.835, 'high': 38.31, 'low': 37.65, 'open': 38.31, 'volume': 12942727, 'adjClose': 10.395167582, 'adjHigh': 10.5256738488, 'adjLow': 10.3443388255, 'adjOpen': 10.5256738488, 'adjVolume': 12942727, 'divCash': 0.0, 'splitFactor': 1.0}, {'date': '2015-07-28T00:00:00.000Z', 'close': 37.72, 'high': 37.92, 'low': 37.27, 'open': 37.64, 'volume': 10333096, 'adjClose': 10.363571328, 'adjHigh': 10.418521335, 'adjLow': 10.2399338121, 'adjOpen': 10.3415913252, 'adjVolume': 10333096, 'divCash': 0.0, 'splitFactor': 1.0}, {'date': '2015-07-29T00:00:00.000Z', 'close': 37.67, 'high': 37.92, 'low': 37.38, 'open': 37.92, 'volume': 10290604, 'adjClose': 10.3498338262, 'adjHigh': 10.418521335, 'adjLow': 10.270156316, 'adjOpen': 10.418521335, 'adjVolume': 10290604, 'divCash': 0.0, 'splitFactor': 1.0}, {'date': '2015-07-30T00:00:00.000Z', 'close': 37.42, 'high': 37.69, 'low': 37.3, 'open': 37.5, 'volume': 9542683, 'adjClose': 10.2811463174, 'adjHigh': 10.3553288269, 'adjLow': 10.2481763132, 'adjOpen': 10.3031263202, 'adjVolume': 9542683, 'divCash': 0.0, 'splitFactor': 1.0}, {'date': '2015-07-31T00:00:00.000Z', 'close': 36.67, 'high': 37.57, 'low': 36.62, 'open': 37.56, 'volume': 15446116, 'adjClose': 10.075083791, 'adjHigh': 10.3223588227, 'adjLow': 10.0613462893, 'adjOpen': 10.3196113223, 'adjVolume': 15446116, 'divCash': 0.0, 'splitFactor': 1.0}, {'date': '2015-08-03T00:00:00.000Z', 'close': 36.69, 'high': 36.9762, 'low': 36.37, 'open': 36.67, 'volume': 9887296, 'adjClose': 10.0805787917, 'adjHigh': 10.1592122518, 'adjLow': 9.9926587805, 'adjOpen': 10.075083791, 'adjVolume': 9887296, 'divCash': 0.0, 'splitFactor': 1.0}, {'date': '2015-08-04T00:00:00.000Z', 'close': 37.12, 'high': 37.21, 'low': 36.6, 'open': 36.61, 'volume': 9051917, 'adjClose': 10.1987213069, 'adjHigh': 10.22344881, 'adjLow': 10.0558512886, 'adjOpen': 10.0585987889, 'adjVolume': 9051917, 'divCash': 0.0, 'splitFactor': 1.0}, {'date': '2015-08-05T00:00:00.000Z', 'close': 37.25, 'high': 37.71, 'low': 37.23, 'open': 37.32, 'volume': 6844018, 'adjClose': 10.2344388114, 'adjHigh': 10.3608238276, 'adjLow': 10.2289438107, 'adjOpen': 10.2536713139, 'adjVolume': 6844018, 'divCash': 0.0, 'splitFactor': 1.0}, {'date': '2015-08-06T00:00:00.000Z', 'close': 36.46, 'high': 37.52, 'low': 36.3, 'open': 37.34, 'volume': 12299702, 'adjClose': 10.0173862836, 'adjHigh': 10.3086213209, 'adjLow': 9.973426278, 'adjOpen': 10.2591663146, 'adjVolume': 12299702, 'divCash': 0.0, 'splitFactor': 1.0}, {'date': '2015-08-07T00:00:00.000Z', 'close': 36.67, 'high': 36.76, 'low': 36.15, 'open': 36.52, 'volume': 11845497, 'adjClose': 10.075083791, 'adjHigh': 10.0998112942, 'adjLow': 9.9322137727, 'adjOpen': 10.0338712857, 'adjVolume': 11845497, 'divCash': 0.0, 'splitFactor': 1.0}, {'date': '2015-08-10T00:00:00.000Z', 'close': 37.15, 'high': 37.69, 'low': 36.87, 'open': 36.87, 'volume': 11351419, 'adjClose': 10.2069638079, 'adjHigh': 10.3553288269, 'adjLow': 10.1300337981, 'adjOpen': 10.1300337981, 'adjVolume': 11351419, 'divCash': 0.0, 'splitFactor': 1.0}, {'date': '2015-08-11T00:00:00.000Z', 'close': 36.03, 'high': 36.77, 'low': 35.731, 'open': 36.74, 'volume': 13833238, 'adjClose': 9.8992437685, 'adjHigh': 10.1025587945, 'adjLow': 9.817093508, 'adjOpen': 10.0943162935, 'adjVolume': 13833238, 'divCash': 0.0, 'splitFactor': 1.0}, {'date': '2015-08-12T00:00:00.000Z', 'close': 34.49, 'high': 34.77, 'low': 33.85, 'open': 34.29, 'volume': 31443155, 'adjClose': 9.4761287143, 'adjHigh': 9.5530587241, 'adjLow': 9.3002886917, 'adjOpen': 9.4211787072, 'adjVolume': 31443155, 'divCash': 0.0, 'splitFactor': 1.0}, {'date': '2015-08-13T00:00:00.000Z', 'close': 35.93, 'high': 36.61, 'low': 34.82, 'open': 35.08, 'volume': 28987668, 'adjClose': 9.871768765, 'adjHigh': 10.0585987889, 'adjLow': 9.5667962259, 'adjOpen': 9.638231235, 'adjVolume': 28987668, 'divCash': 0.0, 'splitFactor': 1.0}, {'date': '2015-08-14T00:00:00.000Z', 'close': 36.24, 'high': 36.345, 'low': 35.72, 'open': 35.82, 'volume': 12241062, 'adjClose': 9.9569412759, 'adjHigh': 9.9857900296, 'adjLow': 9.8140712576, 'adjOpen': 9.8415462611, 'adjVolume': 12241062, 'divCash': 0.0, 'splitFactor': 1.0}, {'date': '2015-08-17T00:00:00.000Z', 'close': 36.095, 'high': 36.24, 'low': 35.765, 'open': 36.24, 'volume': 7933557, 'adjClose': 9.9171025208, 'adjHigh': 9.9569412759, 'adjLow': 9.8264350092, 'adjOpen': 9.9569412759, 'adjVolume': 7933557, 'divCash': 0.0, 'splitFactor': 1.0}, {'date': '2015-08-18T00:00:00.000Z', 'close': 35.69, 'high': 36.1872, 'low': 35.6, 'open': 35.78, 'volume': 11445283, 'adjClose': 9.8058287565, 'adjHigh': 9.942434474, 'adjLow': 9.7811012533, 'adjOpen': 9.8305562597, 'adjVolume': 11445283, 'divCash': 0.0, 'splitFactor': 1.0}, {'date': '2015-08-19T00:00:00.000Z', 'close': 35.19, 'high': 35.67, 'low': 35.025, 'open': 35.67, 'volume': 8976684, 'adjClose': 9.6684537389, 'adjHigh': 9.8003337558, 'adjLow': 9.6231199831, 'adjOpen': 9.8003337558, 'adjVolume': 8976684, 'divCash': 0.0, 'splitFactor': 1.0}, {'date': '2015-08-20T00:00:00.000Z', 'close': 34.1, 'high': 34.95, 'low': 33.87, 'open': 34.77, 'volume': 15604411, 'adjClose': 9.3689762005, 'adjHigh': 9.6025137305, 'adjLow': 9.3057836924, 'adjOpen': 9.5530587241, 'adjVolume': 15604411, 'divCash': 0.0, 'splitFactor': 1.0}, {'date': '2015-08-21T00:00:00.000Z', 'close': 32.93, 'high': 34.02, 'low': 32.91, 'open': 33.58, 'volume': 18373641, 'adjClose': 9.0475186593, 'adjHigh': 9.3469961977, 'adjLow': 9.0420236586, 'adjOpen': 9.2261061822, 'adjVolume': 18373641, 'divCash': 0.0, 'splitFactor': 1.0}, {'date': '2015-08-24T00:00:00.000Z', 'close': 31.31, 'high': 32.28, 'low': 29.0, 'open': 29.02, 'volume': 23163378, 'adjClose': 8.6024236023, 'adjHigh': 8.8689311365, 'adjLow': 7.967751021, 'adjOpen': 7.9732460217, 'adjVolume': 23163378, 'divCash': 0.0, 'splitFactor': 1.0}, {'date': '2015-08-25T00:00:00.000Z', 'close': 31.74, 'high': 33.03, 'low': 31.535, 'open': 32.98, 'volume': 15752294, 'adjClose': 8.7205661174, 'adjHigh': 9.0749936629, 'adjLow': 8.6642423602, 'adjOpen': 9.0612561611, 'adjVolume': 15752294, 'divCash': 0.0, 'splitFactor': 1.0}, {'date': '2015-08-26T00:00:00.000Z', 'close': 32.52, 'high': 32.62, 'low': 31.11, 'open': 32.46, 'volume': 25414501, 'adjClose': 8.9348711449, 'adjHigh': 8.9623461484, 'adjLow': 8.5474735953, 'adjOpen': 8.9183861428, 'adjVolume': 25414501, 'divCash': 0.0, 'splitFactor': 1.0}, {'date': '2015-08-27T00:00:00.000Z', 'close': 33.69, 'high': 33.77, 'low': 32.95, 'open': 33.33, 'volume': 19105076, 'adjClose': 9.2563286861, 'adjHigh': 9.2783086889, 'adjLow': 9.05301366, 'adjOpen': 9.1574186734, 'adjVolume': 19105076, 'divCash': 0.0, 'splitFactor': 1.0}, {'date': '2015-08-28T00:00:00.000Z', 'close': 33.14, 'high': 33.57, 'low': 32.929, 'open': 33.28, 'volume': 9366075, 'adjClose': 9.1052161667, 'adjHigh': 9.2233586819, 'adjLow': 9.0472439093, 'adjOpen': 9.1436811717, 'adjVolume': 9366075, 'divCash': 0.0, 'splitFactor': 1.0}, {'date': '2015-08-31T00:00:00.000Z', 'close': 32.24, 'high': 32.99, 'low': 32.23, 'open': 32.91, 'volume': 13608999, 'adjClose': 8.8579411351, 'adjHigh': 9.0640036615, 'adjLow': 8.8551936347, 'adjOpen': 9.0420236586, 'adjVolume': 13608999, 'divCash': 0.0, 'splitFactor': 1.0}, {'date': '2015-09-01T00:00:00.000Z', 'close': 31.6, 'high': 32.1, 'low': 31.23, 'open': 31.49, 'volume': 19903535, 'adjClose': 8.6821011125, 'adjHigh': 8.8194761301, 'adjLow': 8.5804435995, 'adjOpen': 8.6518786086, 'adjVolume': 19903535, 'divCash': 0.0, 'splitFactor': 1.0}, {'date': '2015-09-02T00:00:00.000Z', 'close': 31.77, 'high': 32.03, 'low': 31.38, 'open': 32.01, 'volume': 15688093, 'adjClose': 8.7288086185, 'adjHigh': 8.8002436277, 'adjLow': 8.6216561048, 'adjOpen': 8.794748627, 'adjVolume': 15688093, 'divCash': 0.0, 'splitFactor': 1.0}, {'date': '2015-09-03T00:00:00.000Z', 'close': 32.54, 'high': 32.745, 'low': 31.8, 'open': 31.86, 'volume': 13748876, 'adjClose': 8.9403661456, 'adjHigh': 8.9966899028, 'adjLow': 8.7370511196, 'adjOpen': 8.7535361217, 'adjVolume': 13748876, 'divCash': 0.0, 'splitFactor': 1.0}, {'date': '2015-09-04T00:00:00.000Z', 'close': 31.58, 'high': 32.29, 'low': 31.44, 'open': 32.0, 'volume': 13854141, 'adjClose': 8.6766061118, 'adjHigh': 8.8716786368, 'adjLow': 8.6381411069, 'adjOpen': 8.7920011266, 'adjVolume': 13854141, 'divCash': 0.0, 'splitFactor': 1.0}, {'date': '2015-09-08T00:00:00.000Z', 'close': 30.9, 'high': 32.83, 'low': 30.86, 'open': 32.2, 'volume': 26873863, 'adjClose': 8.4897760879, 'adjHigh': 9.0200436558, 'adjLow': 8.4787860865, 'adjOpen': 8.8469511336, 'adjVolume': 26873863, 'divCash': 0.0, 'splitFactor': 1.0}, {'date': '2015-09-09T00:00:00.000Z', 'close': 31.52, 'high': 31.8, 'low': 30.35, 'open': 30.4, 'volume': 47058537, 'adjClose': 8.6601211097, 'adjHigh': 8.7370511196, 'adjLow': 8.3386635685, 'adjOpen': 8.3524010703, 'adjVolume': 47058537, 'divCash': 0.0, 'splitFactor': 1.0}, {'date': '2015-09-10T00:00:00.000Z', 'close': 31.15, 'high': 31.59, 'low': 31.03, 'open': 31.35, 'volume': 14330896, 'adjClose': 8.5584635967, 'adjHigh': 8.6793536122, 'adjLow': 8.5254935925, 'adjOpen': 8.6134136037, 'adjVolume': 14330896, 'divCash': 0.0, 'splitFactor': 1.0}, {'date': '2015-09-11T00:00:00.000Z', 'close': 31.43, 'high': 31.43, 'low': 30.63, 'open': 31.09, 'volume': 14365370, 'adjClose': 8.6353936065, 'adjHigh': 8.6353936065, 'adjLow': 8.4155935784, 'adjOpen': 8.5419785946, 'adjVolume': 14365370, 'divCash': 0.0, 'splitFactor': 1.0}, {'date': '2015-09-14T00:00:00.000Z', 'close': 30.32, 'high': 30.92, 'low': 30.0, 'open': 30.68, 'volume': 22186926, 'adjClose': 8.3304210675, 'adjHigh': 8.4952710886, 'adjLow': 8.2425010562, 'adjOpen': 8.4293310801, 'adjVolume': 22186926, 'divCash': 0.0, 'splitFactor': 1.0}, {'date': '2015-09-15T00:00:00.000Z', 'close': 31.04, 'high': 31.225, 'low': 29.41, 'open': 29.72, 'volume': 25661630, 'adjClose': 8.5282410928, 'adjHigh': 8.5790698493, 'adjLow': 8.0803985354, 'adjOpen': 8.1655710463, 'adjVolume': 25661630, 'divCash': 0.0, 'splitFactor': 1.0}, {'date': '2015-09-16T00:00:00.000Z', 'close': 31.4, 'high': 31.77, 'low': 30.99, 'open': 31.14, 'volume': 22179724, 'adjClose': 8.6271511055, 'adjHigh': 8.7288086185, 'adjLow': 8.514503591, 'adjOpen': 8.5557160963, 'adjVolume': 22179724, 'divCash': 0.0, 'splitFactor': 1.0}, {'date': '2015-09-17T00:00:00.000Z', 'close': 30.93, 'high': 31.33, 'low': 30.81, 'open': 31.31, 'volume': 17094184, 'adjClose': 8.4980185889, 'adjHigh': 8.607918603, 'adjLow': 8.4650485847, 'adjOpen': 8.6024236023, 'adjVolume': 17094184, 'divCash': 0.0, 'splitFactor': 1.0}, {'date': '2015-09-18T00:00:00.000Z', 'close': 30.74, 'high': 30.8, 'low': 30.41, 'open': 30.51, 'volume': 20538316, 'adjClose': 8.4458160822, 'adjHigh': 8.4623010844, 'adjLow': 8.3551485706, 'adjOpen': 8.3826235741, 'adjVolume': 20538316, 'divCash': 0.0, 'splitFactor': 1.0}, {'date': '2015-09-21T00:00:00.000Z', 'close': 31.17, 'high': 31.735, 'low': 30.88, 'open': 31.2, 'volume': 18744953, 'adjClose': 8.5639585974, 'adjHigh': 8.7191923673, 'adjLow': 8.4842810872, 'adjOpen': 8.5722010984, 'adjVolume': 18744953, 'divCash': 0.0, 'splitFactor': 1.0}, {'date': '2015-09-22T00:00:00.000Z', 'close': 30.4, 'high': 30.92, 'low': 30.17, 'open': 30.78, 'volume': 15614931, 'adjClose': 8.3524010703, 'adjHigh': 8.4952710886, 'adjLow': 8.2892085622, 'adjOpen': 8.4568060837, 'adjVolume': 15614931, 'divCash': 0.0, 'splitFactor': 1.0}, {'date': '2015-09-23T00:00:00.000Z', 'close': 29.74, 'high': 30.57, 'low': 29.63, 'open': 30.56, 'volume': 12755387, 'adjClose': 8.171066047, 'adjHigh': 8.3991085763, 'adjLow': 8.1408435432, 'adjOpen': 8.3963610759, 'adjVolume': 12755387, 'divCash': 0.0, 'splitFactor': 1.0}, {'date': '2015-09-24T00:00:00.000Z', 'close': 29.34, 'high': 29.57, 'low': 28.85, 'open': 29.47, 'volume': 19109920, 'adjClose': 8.061166033, 'adjHigh': 8.1243585411, 'adjLow': 7.9265385157, 'adjOpen': 8.0968835375, 'adjVolume': 19109920, 'divCash': 0.0, 'splitFactor': 1.0}, {'date': '2015-09-25T00:00:00.000Z', 'close': 29.13, 'high': 29.71, 'low': 28.905, 'open': 29.66, 'volume': 12817501, 'adjClose': 8.0034685256, 'adjHigh': 8.162823546, 'adjLow': 7.9416497676, 'adjOpen': 8.1490860442, 'adjVolume': 12817501, 'divCash': 0.0, 'splitFactor': 1.0}, {'date': '2015-09-28T00:00:00.000Z', 'close': 27.6, 'high': 29.22, 'low': 27.2, 'open': 29.03, 'volume': 49541270, 'adjClose': 7.5831009717, 'adjHigh': 8.0281960287, 'adjLow': 7.4732009576, 'adjOpen': 7.975993522, 'adjVolume': 49541270, 'divCash': 0.0, 'splitFactor': 1.0}, {'date': '2015-09-29T00:00:00.000Z', 'close': 28.26, 'high': 29.23, 'low': 27.85, 'open': 28.58, 'volume': 41895407, 'adjClose': 7.7644359949, 'adjHigh': 8.0309435291, 'adjLow': 7.6517884805, 'adjOpen': 7.8523560062, 'adjVolume': 41895407, 'divCash': 0.0, 'splitFactor': 1.0}, {'date': '2015-09-30T00:00:00.000Z', 'close': 28.91, 'high': 29.11, 'low': 28.49, 'open': 28.65, 'volume': 18317909, 'adjClose': 7.9430235178, 'adjHigh': 7.9979735249, 'adjLow': 7.827628503, 'adjOpen': 7.8715885087, 'adjVolume': 18317909, 'divCash': 0.0, 'splitFactor': 1.0}, {'date': '2015-10-01T00:00:00.000Z', 'close': 28.91, 'high': 29.0, 'low': 28.44, 'open': 28.95, 'volume': 14467626, 'adjClose': 7.9430235178, 'adjHigh': 7.967751021, 'adjLow': 7.8138910013, 'adjOpen': 7.9540135192, 'adjVolume': 14467626, 'divCash': 0.0, 'splitFactor': 1.0}, {'date': '2015-10-02T00:00:00.000Z', 'close': 30.71, 'high': 30.71, 'low': 28.43, 'open': 28.62, 'volume': 29250543, 'adjClose': 8.4375735812, 'adjHigh': 8.4375735812, 'adjLow': 7.8111435009, 'adjOpen': 7.8633460076, 'adjVolume': 29250543, 'divCash': 0.0, 'splitFactor': 1.0}, {'date': '2015-10-05T00:00:00.000Z', 'close': 30.85, 'high': 31.2, 'low': 30.35, 'open': 30.8, 'volume': 12883305, 'adjClose': 8.4760385861, 'adjHigh': 8.5722010984, 'adjLow': 8.3386635685, 'adjOpen': 8.4623010844, 'adjVolume': 12883305, 'divCash': 0.0, 'splitFactor': 1.0}, {'date': '2015-10-06T00:00:00.000Z', 'close': 30.955, 'high': 31.185, 'low': 30.66, 'open': 30.79, 'volume': 10963857, 'adjClose': 8.5048873398, 'adjHigh': 8.5680798479, 'adjLow': 8.4238360794, 'adjOpen': 8.459553584, 'adjVolume': 10963857, 'divCash': 0.0, 'splitFactor': 1.0}, {'date': '2015-10-07T00:00:00.000Z', 'close': 31.87, 'high': 31.99, 'low': 31.21, 'open': 31.31, 'volume': 12224842, 'adjClose': 8.756283622, 'adjHigh': 8.7892536262, 'adjLow': 8.5749485988, 'adjOpen': 8.6024236023, 'adjVolume': 12224842, 'divCash': 0.0, 'splitFactor': 1.0}, {'date': '2015-10-08T00:00:00.000Z', 'close': 32.37, 'high': 32.5, 'low': 31.73, 'open': 31.79, 'volume': 14245376, 'adjClose': 8.8936586396, 'adjHigh': 8.9293761442, 'adjLow': 8.7178186171, 'adjOpen': 8.7343036192, 'adjVolume': 14245376, 'divCash': 0.0, 'splitFactor': 1.0}, {'date': '2015-10-09T00:00:00.000Z', 'close': 32.52, 'high': 32.69, 'low': 31.99, 'open': 32.35, 'volume': 11830351, 'adjClose': 8.9348711449, 'adjHigh': 8.9815786509, 'adjLow': 8.7892536262, 'adjOpen': 8.8881636389, 'adjVolume': 11830351, 'divCash': 0.0, 'splitFactor': 1.0}, {'date': '2015-10-12T00:00:00.000Z', 'close': 32.86, 'high': 33.02, 'low': 32.55, 'open': 32.71, 'volume': 12580273, 'adjClose': 9.0282861569, 'adjHigh': 9.0722461625, 'adjLow': 8.943113646, 'adjOpen': 8.9870736516, 'adjVolume': 12580273, 'divCash': 0.0, 'splitFactor': 1.0}, {'date': '2015-10-13T00:00:00.000Z', 'close': 32.34, 'high': 32.825, 'low': 32.32, 'open': 32.56, 'volume': 15873827, 'adjClose': 8.8854161386, 'adjHigh': 9.0186699056, 'adjLow': 8.8799211379, 'adjOpen': 8.9458611463, 'adjVolume': 15873827, 'divCash': 0.0, 'splitFactor': 1.0}, {'date': '2015-10-14T00:00:

In [104]:
def load_yahoo_price(ticker):
    path = Path(DIR_PRICES) / f"{ticker}.csv"
    if not path.exists():
        raise FileNotFoundError(f"Yahoo price file missing: {path}")
    df = pd.read_csv(path, parse_dates=[0])
    df.rename(columns={df.columns[0]: "date"}, inplace=True)
    df.set_index("date", inplace=True)
    price_cols = [c for c in df.columns if c.lower() in {"close", ticker.lower()}]
    if not price_cols:
        raise ValueError(f"Yahoo file for {ticker} has no Close-like column")
    df = df.rename(columns={price_cols[0]: "Close"})
    return df

In [108]:
import requests
import yfinance as yf


def fetch_tiingo(ticker, start_date, end_date):
    url = f"https://api.tiingo.com/tiingo/daily/{ticker}/prices"
    params = {
        'startDate': start_date,
        'endDate': end_date,
        'token': TIINGO_TOKEN,
        'resampleFreq': 'daily'
    }
    response = requests.get(url, params=params)
    if response.status_code != 200:
        raise ValueError(f"Tiingo API error for {ticker}: {response.status_code}")
    data = response.json()
    df = pd.DataFrame(data)
    df['date'] = pd.to_datetime(df['date'])
    df.set_index('date', inplace=True)
    df.index = df.index.tz_localize(None)
    if 'close' not in df.columns:
        raise ValueError(f"Tiingo response for {ticker} has no close column")
    return df[['close']].rename(columns={'close': 'Close'})


def fetch_yahoo_unadjusted(ticker, start_date, end_date):
    raw = yf.download(
        ticker,
        start=start_date,
        end=end_date,
        auto_adjust=False,
        progress=False,
    )
    if raw is None or len(raw) == 0:
        raise ValueError(f"Yahoo returned no data for {ticker} between {start_date} and {end_date}")
    if hasattr(raw.columns, 'levels'):
        raw.columns = raw.columns.get_level_values(0)
    if 'Close' not in raw.columns:
        raise ValueError(f"Yahoo data for {ticker} has no Close column")
    df = raw[['Close']].copy()
    df.index = pd.DatetimeIndex(df.index).tz_localize(None)
    return df


def load_base_price(ticker):
    if ticker not in db_full.columns:
        raise ValueError(f"Ticker {ticker} not in base data")
    df = db_full[[ticker]].copy()
    df.index = pd.DatetimeIndex(df.index)
    return df.rename(columns={ticker: 'Close'})

# Validate unadjusted close prices using Yahoo data prior to 2016,
# comparing the base with both Yahoo and Tiingo for the overlapping dates.
VALIDATE_TICKERS = ['AAPL', 'MSFT', 'GOOGL', 'AMZN', 'JNJ', 'XOM']

for ticker in VALIDATE_TICKERS:
    try:
        if ticker not in db_full.columns:
            print(f"{ticker}: not in base, skipping")
            continue

        base_df = load_base_price(ticker).dropna()
        if len(base_df) < 10:
            print(f"{ticker}: not enough base data, skipping")
            continue

        start_date = base_df.index.min().strftime("%Y-%m-%d")
        end_date = (base_df.index.max() + pd.Timedelta(days=1)).strftime("%Y-%m-%d")

        yahoo_df = fetch_yahoo_unadjusted(ticker, start_date, end_date)
        tiingo_df = fetch_tiingo(ticker, start_date, end_date)

        common_dates = base_df.index.intersection(yahoo_df.index).intersection(tiingo_df.index)
        if len(common_dates) == 0:
            raise ValueError("No overlapping dates between base, Yahoo, and Tiingo")

        base_prices = base_df.loc[common_dates, 'Close']
        yahoo_prices = yahoo_df.loc[common_dates, 'Close']
        tiingo_prices = tiingo_df.loc[common_dates, 'Close']

        diff_yahoo_base = (yahoo_prices - base_prices).abs()
        diff_tiingo_base = (tiingo_prices - base_prices).abs()
        diff_yahoo_tiingo = (yahoo_prices - tiingo_prices).abs()

        print(f"{ticker}: {common_dates.min().date()} → {common_dates.max().date()} | rows {len(common_dates)}")
        print(f"  max(|Yahoo-Base|)   = {diff_yahoo_base.max():.4f}")
        print(f"  max(|Tiingo-Base|)  = {diff_tiingo_base.max():.4f}")
        print(f"  max(|Yahoo-Tiingo|) = {diff_yahoo_tiingo.max():.4f}")

        if diff_yahoo_base.max() > 0.01 or diff_tiingo_base.max() > 0.01:
            print(f"  WARNING: large difference on {ticker}")
            print(f"  Top Yahoo/Base mismatches:\n{diff_yahoo_base.sort_values(ascending=False).head(5)}")
    except Exception as e:
        print(f"{ticker}: ERROR — {e}")

AAPL: 1990-01-02 → 2015-12-24 | rows 6219
  max(|Yahoo-Base|)   = 112.0962
  max(|Tiingo-Base|)  = 610.0971
  max(|Yahoo-Tiingo|) = 677.0250
  WARNING: large difference on AAPL
  Top Yahoo/Base mismatches:
2014-02-19    112.096214
2014-04-22    111.953214
2014-02-20    111.498957
2014-04-23    110.138328
2014-02-24    109.895130
Name: Close, dtype: float64
MSFT: 1990-01-02 → 2015-12-24 | rows 6219
  max(|Yahoo-Base|)   = 43.1469
  max(|Tiingo-Base|)  = 151.0660
  max(|Yahoo-Tiingo|) = 147.8906
  WARNING: large difference on MSFT
  Top Yahoo/Base mismatches:
2000-01-03    43.14685
2000-01-05    40.00545
2000-01-04    39.58610
2000-01-07    38.64345
2000-01-18    38.29115
Name: Close, dtype: float64
GOOGL: 2004-08-19 → 2015-12-24 | rows 2646
  max(|Yahoo-Base|)   = 755.6680
  max(|Tiingo-Base|)  = 669.0800
  max(|Yahoo-Tiingo|) = 1189.6352
  WARNING: large difference on GOOGL
  Top Yahoo/Base mismatches:
2015-12-24    755.668000
2015-11-27    745.191501
2015-12-23    743.814501
2015-12-02    740.317498
2015-11-30    739.707498
Name: Close, dtype: float64
AMZN: 1997-05-15 → 2015-12-24 | rows 4408
  max(|Yahoo-Base|)   = 660.8305
  max(|Tiingo-Base|)  = 298.3580
  max(|Yahoo-Tiingo|) = 645.1070
  WARNING: large difference on AMZN
  Top Yahoo/Base mismatches:
2015-12-24    660.830500
2015-11-20    645.567499
2015-11-27    645.397002
2015-12-04    643.698000
2015-12-14    642.874500
Name: Close, dtype: float64
JNJ: 1990-01-02 → 2015-12-24 | rows 6219
  max(|Yahoo-Base|)   = 26.3493
  max(|Tiingo-Base|)  = 109.4620
  max(|Yahoo-Tiingo|) = 101.8331
  WARNING: large difference on JNJ
  Top Yahoo/Base mismatches:
2005-04-07    26.349298
2008-04-22    26.260398
2008-04-23    26.224802
2005-04-15    26.160202
2005-04-14    26.158700
Name: Close, dtype: float64
XOM: 1990-01-02 → 2015-12-24 | rows 6219
  max(|Yahoo-Base|)   = 39.1129
  max(|Tiingo-Base|)  = 87.0392
  max(|Yahoo-Tiingo|) = 82.0263
  WARNING: large difference on XOM
  Top Yahoo/Base mismatches:
2008-04-21    39.112902
2008-04-16    38.893699
2008-04-17    38.583097
2008-04-18    38.486000
2008-04-22    38.450699
Name: Close, dtype: float64